import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig, devices } from '@playwright/test';
import { e2ePlatformHostname } from './e2e/hosts';

const repoRoot = fileURLToPath(new URL('../../', import.meta.url));

/**
 * Load `.env.local` (generated by `bash scripts/local-env.sh --write`) before any spec is collected.
 * `fixtures.ts` throws at import time when `SEED_PASSWORD` is missing, and `platform.spec.ts` needs
 * `SUPER_ADMIN_*`; without this a clean machine could run `pnpm db:seed` and the API suite and still
 * be told to export two variables by hand for the e2e (01-08). Anything already exported wins, which
 * is how CI passes its own values.
 */
const envFile = fileURLToPath(new URL('.env.local', import.meta.url));
const exportedPlatformHost = process.env.PLATFORM_HOST;
if (existsSync(envFile)) process.loadEnvFile(envFile);

/**
 * PLATFORM_HOST for the servers this run launches (07-12, WINDOWS 59). The harness owns it: the
 * specs browse `e2ePlatformHostname()` (`./e2e/hosts.ts`, the one source of the e2e origins), so the
 * API, the web, the worker `ensureWorker()` spawns and the PWA config's `next start` must all be told
 * that same host. Playwright spawns every `webServer` with `...process.env`, and neither Node's
 * `--env-file-if-exists` nor `next dev` lets an env file override a variable already set, so setting
 * it here reaches all of them.
 *
 * - An EXPORTED value always wins and is never touched (CI passes its own; a deliberate override stays
 *   possible).
 * - Otherwise a value that came from `.env.local` is replaced, with one warning line that names the
 *   harness host and never the file's value (T-07-77).
 *
 * Why this does not mask a shipped-configuration defect: production's PLATFORM_HOST is a Vercel and
 * Cloud Run variable (DEPLOY.md) this harness never reads; CI writes the same value from
 * `scripts/local-env.sh` and `.env.example` documents it; the platform-shell logic in
 * `lib/tenant-host.ts` is still exercised end to end by every platform-host case and by its unit
 * test. What the harness no longer catches is a stale value in a developer's own `.env.local`, which
 * affects only a hand-run `next dev`. `bash scripts/local-env.sh --write` is NOT the remedy for that:
 * it rewrites both env files wholesale from its template and drops hand-set values (Mux keys).
 */
if (exportedPlatformHost === undefined) {
  const harnessPlatformHost = e2ePlatformHostname();
  const fromFile = process.env.PLATFORM_HOST;
  if (fromFile !== undefined && fromFile !== harnessPlatformHost) {
    console.warn(
      `[e2e] this run serves the platform shell on ${harnessPlatformHost} (the host the specs browse) instead of the PLATFORM_HOST in apps/web/.env.local; a hand-run \`next dev\` still reads that file.`,
    );
  }
  process.env.PLATFORM_HOST = harnessPlatformHost;
}

/**
 * CSP_MODE for the web servers this run launches (08-08, D-346): every spec, in both this config and
 * the production-build PWA config that imports it, runs under the ENFORCED Content Security Policy,
 * so a script, frame or connection the policy would block fails the suite instead of only producing
 * a report. Production ships `report-only` first (DEPLOY.md). An exported value still wins.
 * `reuseExistingServer` means a web server you started yourself keeps whatever mode it was given.
 */
process.env.CSP_MODE ??= 'enforce';

/**
 * INSTALL_GATE for the web servers this run launches (quick 261007-kyp): every spec drives the
 * iPhone 14 and Pixel 7 presets outside standalone, which the install gate would replace with the
 * "instale o app" screen. The gate has its own unit and component tests (Chromium cannot emulate
 * display-mode standalone). An exported value still wins; a dev server you started yourself keeps
 * its own environment, which is `off` under `next dev` anyway.
 */
process.env.INSTALL_GATE ??= 'off';

/**
 * `baseURL` is the rede-demo TENANT host (D-20). Chromium resolves every `*.localhost` name to loopback
 * (RFC 6761), so no `/etc/hosts` entry is needed and the two seed tenants plus the platform host are
 * distinct origins with separate cookies. Readiness is probed on plain `localhost` (a generic host that
 * needs no API lookup); the Next dev server binds one port for all of them.
 * Node-side helpers must use `127.0.0.1` URLs: Node's resolver does not special-case `*.localhost`.
 *
 * Projects (02-16): `pixel-chromium` (Pixel 7 on Chromium) exists for ROADMAP Phase 2 criterion 1 —
 * "on a phone" means iPhone 14 AND Pixel 7 — and is scoped to the two Phase 2 smoke specs
 * (`branding.spec.ts`, `phase2-smoke.spec.ts`) so the rest of the suite keeps Phase 1's two-project
 * cost. The worker is NOT a webServer: specs that need icon derivation (`kernel.branding-derive-icons`)
 * call `ensureWorker()` from `./e2e/worker.ts` and stop it in `afterAll` (02-14 decision).
 * `PLAYWRIGHT_REPORT_DIR` / `PLAYWRIGHT_OUTPUT_DIR` let CI keep the dev-server run and the
 * production-build run (`playwright.pwa.config.ts` inherits these) in separate folders.
 */
const REPORT_DIR = process.env.PLAYWRIGHT_REPORT_DIR ?? 'playwright-report';
const OUTPUT_DIR = process.env.PLAYWRIGHT_OUTPUT_DIR ?? 'test-results';

export default defineConfig({
  testDir: './e2e',
  retries: 0,
  fullyParallel: false,
  workers: 1,
  reporter: process.env.CI
    ? [['github'], ['html', { open: 'never', outputFolder: REPORT_DIR }]]
    : 'list',
  outputDir: OUTPUT_DIR,
  expect: { timeout: 10_000 },
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://rede-demo.localhost:3000',
    trace: 'retain-on-failure',
  },
  projects: [
    // iPhone 14 viewport/UA/touch on Chromium (the device preset defaults to WebKit).
    { name: 'mobile-chromium', use: { ...devices['iPhone 14'], browserName: 'chromium' } },
    // Pixel 7 on Chromium — the Android phone of criterion 1; only the two Phase 2 smoke specs.
    {
      name: 'pixel-chromium',
      testMatch: /[\\/](branding|phase2-smoke)\.spec\.ts$/,
      use: { ...devices['Pixel 7'], browserName: 'chromium' },
    },
    { name: 'desktop-chromium', use: { ...devices['Desktop Chrome'] } },
  ],
  webServer: [
    {
      command: 'pnpm --filter @rede-social/api dev',
      url: 'http://localhost:8787/v1/health',
      reuseExistingServer: true,
      cwd: repoRoot,
      timeout: 60_000,
    },
    {
      command: 'pnpm dev',
      url: 'http://localhost:3000/entrar',
      reuseExistingServer: true,
      timeout: 120_000,
    },
  ],
});
