// Regenerates `lib/google-fonts.ts`, the Google Fonts families a tenant's titles may use.
//
//   node scripts/google-fonts.mjs [metadata.json]
//
// Reads Google Fonts' public family metadata (the list fonts.google.com itself loads; no API key)
// or a saved copy of it, keeps the families the app can render as a title and writes them most
// popular first. Run from apps/web, then `pnpm exec biome format --write lib/google-fonts.ts`.
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'https://fonts.google.com/metadata/fonts';
const OUTPUT = new URL('../lib/google-fonts.ts', import.meta.url);

/** Google's category → the catalogue's. */
const CATEGORY = {
  'Sans Serif': 'sans',
  Serif: 'serif',
  Display: 'display',
  Handwriting: 'handwriting',
  Monospace: 'mono',
};
/**
 * The generic Noto families. Every other Noto family adds one script to the same Latin design, so
 * in a pt-BR title it would only repeat these.
 */
const NOTO_KEPT = new Set([
  'Noto Sans',
  'Noto Serif',
  'Noto Sans Display',
  'Noto Serif Display',
  'Noto Sans Mono',
]);
/**
 * Families that draw icons, barcodes, blocks, charts or waveforms instead of letters. Whole words
 * where a name could hide them ("Niconne" is a script with letters).
 */
const NOT_LETTERS =
  /\b(?:icons?|symbols?|emoji)\b|barcode|^flow |^redacted|charted|yarndings|wavefont|linefont/i;

async function readMetadata(path) {
  let text;
  if (path) {
    text = readFileSync(path, 'utf8');
  } else {
    const res = await fetch(SOURCE);
    if (!res.ok) throw new Error(`${SOURCE} answered ${res.status}`);
    text = await res.text();
  }
  // The endpoint may prefix the JSON with the anti-hijacking line `)]}'`.
  if (text.startsWith(")]}'")) text = text.slice(text.indexOf('\n') + 1);
  return JSON.parse(text).familyMetadataList;
}

/** The upright (non-italic) weights a family ships, ascending. */
function uprightWeights(family) {
  return Object.keys(family.fonts)
    .filter((style) => /^\d+$/.test(style))
    .map(Number)
    .sort((a, b) => a - b);
}

/**
 * What a title can use: the `latin` subset (the Portuguese accents; a family whose main script is
 * another one, like Poppins with Devanagari, still ships it whole), open source, at least one
 * upright style, and letters (no colour, symbol, barcode or placeholder font).
 */
function usable(family) {
  return (
    (family.subsets ?? []).includes('latin') &&
    (family.colorCapabilities ?? []).length === 0 &&
    family.isOpenSource !== false &&
    !(family.classifications ?? []).includes('Symbols') &&
    !(family.isNoto && !NOTO_KEPT.has(family.family)) &&
    !NOT_LETTERS.test(family.family) &&
    CATEGORY[family.category] !== undefined &&
    uprightWeights(family).length > 0
  );
}

const families = (await readMetadata(process.argv[2]))
  .filter(usable)
  .sort((a, b) => a.popularity - b.popularity || a.family.localeCompare(b.family));

for (const family of families) {
  // The name ends up quoted in CSS and in a URL: anything beyond letters, digits and spaces stops
  // the run instead of reaching the page.
  if (!/^[A-Za-z0-9 ]{1,60}$/.test(family.family)) {
    throw new Error(`unexpected family name: ${family.family}`);
  }
}
if (new Set(families.map((family) => family.family)).size !== families.length) {
  throw new Error('duplicate family name');
}

const date = new Date().toISOString().slice(0, 10);
const rows = families
  .map(
    (family) =>
      `  ['${family.family}', '${CATEGORY[family.category]}', [${uprightWeights(family).join(', ')}]],`,
  )
  .join('\n');

writeFileSync(
  OUTPUT,
  `// GENERATED by \`scripts/google-fonts.mjs\` on ${date}, from
// ${SOURCE}.
// Do not edit by hand: run the script again to refresh the list.
import type { GoogleFont } from './title-font';

/**
 * Every Google Fonts family a tenant's titles may use (${families.length}): the \`latin\` subset
 * (the Portuguese accents), open source, at least one upright style, and no colour, symbol,
 * barcode or placeholder font. Most popular first. Each entry is the family, its category and the
 * upright weights it ships: the stylesheet request may only ask for those (Google answers HTTP 400
 * to a weight the family does not have).
 */
export const GOOGLE_FONTS: readonly GoogleFont[] = [
${rows}
];
`,
);

const byCategory = {};
for (const family of families) {
  const key = CATEGORY[family.category];
  byCategory[key] = (byCategory[key] ?? 0) + 1;
}
console.log(`${families.length} families written to lib/google-fonts.ts`, byCategory);
