/**
 * One-shot backfill of EVENT-07 reminders (07-05, RESEARCH open question 1, RESOLVED).
 * Run: `pnpm exec tsx scripts/arm-event-reminders.ts [--dry-run]`.
 *
 * Events created BEFORE the reminders shipped have no `events.reminder` jobs: the events module arms
 * them inside its own write transactions (create, a moved start, a reactivation), and nothing ran
 * those for older rows. This script arms the same jobs for every active, upcoming, not-removed event
 * of EVERY tenant, through the admin lane (scripts may use it, T-07-32), so an operator runs it once
 * after the deploy (07-11 writes the step into DEPLOY.md). It is optional: an event edited or
 * reactivated after the deploy re-arms itself.
 *
 * **Idempotent.** It uses the module's own payload, `startAfter` and singleton key
 * (`{eventId}:{window}:{startsAtEpochSeconds}`), and every queue has the `short` policy, so a job
 * still waiting for the same start is never duplicated: running this twice arms nothing new. A
 * window whose fire time is already past is SKIPPED, never sent late (the module's rule). Even a
 * duplicate that slipped through would notify nobody twice: the fan-out dedupes per
 * `(event, window, user)`.
 *
 * **The module's rules are RESTATED here, not imported** (the `seed.ts` precedent): the root
 * workspace may not depend on a `module`-tagged package, or `turbo boundaries` mis-attributes the
 * edge and the MOD-02 gate goes red. The four facts restated below mirror
 * `packages/modules/events/{contracts/index.ts,server/reminders.ts}` exactly: the queue name, the two
 * window offsets, the key format and the payload shape (ids, the window and the instant in the
 * module's microsecond ISO format, never a title, T-07-31). Edit both together.
 *
 * Connection: the same env the seed reads (`apps/api/.env.local` locally, the process environment in
 * production). `DATABASE_URL` is never printed. The pg-boss instance is the kernel's `createBoss`
 * (schema `pgboss`, `migrate: false`: the runtime issues no DDL), started without supervision or
 * scheduling, and stopped before exit.
 *
 * Output: ONE summary line, `{ events, armed, skipped }` (`skipped` = past windows plus windows
 * whose job was already waiting). `--dry-run` reads and plans only: nothing is enqueued, and `armed`
 * is the number of windows a real run would try to arm.
 */
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

// Load the local stack values (generated by scripts/local-env.sh) before any kernel module reads env.
// Variables already present in the process environment take precedence over the file.
const envFile = resolve(process.cwd(), 'apps/api/.env.local');
if (existsSync(envFile)) process.loadEnvFile(envFile);

const dryRun = process.argv.includes('--dry-run');

const { sql } = await import('drizzle-orm');
const { withAdminTx } = await import('@rede-social/core/db/admin-tx');
const { sqlClient } = await import('@rede-social/core/db');
const { env } = await import('@rede-social/core/server/env');
const { createBoss, createQueues } = await import('@rede-social/core/server/jobs/boss');

/** `EVENTS_QUEUES.reminder`, restated. */
const REMINDER_QUEUE = 'events.reminder';

/** `EVENT_REMINDER_WINDOWS` and `EVENT_REMINDER_OFFSET_MS`, restated, in firing order. */
const WINDOWS = [
  { window: '24h', offsetMs: 24 * 60 * 60 * 1000 },
  { window: '1h', offsetMs: 60 * 60 * 1000 },
] as const;

type UpcomingEvent = { id: string; tenant_id: string; starts_at: string };

// Every tenant's active, upcoming, not-removed event, the start in the module's own ISO format.
const upcoming = await withAdminTx((tx) =>
  tx.execute<UpcomingEvent>(sql`
    select id::text as id,
           tenant_id::text as tenant_id,
           to_char(starts_at at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') as starts_at
      from public.events
     where status = 'active'
       and deleted_at is null
       and starts_at > now()
     order by starts_at, id`),
);

const nowMs = Date.now();
const plan: {
  payload: { tenantId: string; eventId: string; window: string; startsAt: string };
  startAfter: Date;
  singletonKey: string;
}[] = [];
let skipped = 0;

for (const event of upcoming) {
  const startsAtMs = Date.parse(event.starts_at);
  for (const { window, offsetMs } of WINDOWS) {
    const fireAtMs = startsAtMs - offsetMs;
    // `planEventReminders`' rule: a window at or before now is skipped, never sent late.
    if (!Number.isFinite(fireAtMs) || fireAtMs <= nowMs) {
      skipped += 1;
      continue;
    }
    plan.push({
      payload: {
        tenantId: event.tenant_id,
        eventId: event.id,
        window,
        startsAt: event.starts_at,
      },
      startAfter: new Date(fireAtMs),
      singletonKey: `${event.id}:${window}:${Math.floor(startsAtMs / 1000)}`,
    });
  }
}

let armed = 0;
if (dryRun) {
  armed = plan.length;
} else if (plan.length > 0) {
  const boss = createBoss({
    connectionString: env.DATABASE_URL,
    max: 1,
    supervise: false,
    schedule: false,
  });
  // A connection-level error must not print the connection string: only its message.
  boss.on('error', (error: unknown) => {
    console.error('arm-event-reminders: pg-boss error', {
      error: error instanceof Error ? error.message : String(error),
    });
  });
  await boss.start();
  try {
    // Idempotent, and verifies the `short` policy the idempotency above relies on.
    await createQueues(boss, [REMINDER_QUEUE]);
    for (const job of plan) {
      const id = await boss.send(REMINDER_QUEUE, job.payload, {
        startAfter: job.startAfter,
        singletonKey: job.singletonKey,
      });
      // `null`: a job for the same start is still waiting (the `short` policy dropped this one).
      if (id) armed += 1;
      else skipped += 1;
    }
  } finally {
    await boss.stop({ graceful: false });
  }
}

console.log(
  `arm-event-reminders${dryRun ? ' (dry run)' : ''}: ${JSON.stringify({
    events: upcoming.length,
    armed,
    skipped,
  })}`,
);
await sqlClient.end();
