#!/usr/bin/env bash
# Prints an `.env.local` block for apps/api and apps/web from the running local Supabase stack.
# Usage: bash scripts/local-env.sh > apps/api/.env.local && bash scripts/local-env.sh > apps/web/.env.local
set -euo pipefail
cd "$(dirname "$0")/.."

STATUS="$(pnpm --silent supabase status -o env)"

get() {
  printf '%s\n' "$STATUS" | grep -E "^$1=" | head -1 | cut -d= -f2- | tr -d '"'
}

SUPABASE_URL="$(get API_URL)"
SERVICE_KEY="$(get SERVICE_ROLE_KEY)"
[ -z "$SERVICE_KEY" ] && SERVICE_KEY="$(get SECRET_KEY)"
PUBLISHABLE_KEY="$(get ANON_KEY)"
[ -z "$PUBLISHABLE_KEY" ] && PUBLISHABLE_KEY="$(get PUBLISHABLE_KEY)"

if [ -z "$SUPABASE_URL" ] || [ -z "$SERVICE_KEY" ] || [ -z "$PUBLISHABLE_KEY" ]; then
  echo "local-env: could not read API_URL / service key / publishable key from 'supabase status -o env'" >&2
  exit 1
fi

cat <<ENV
# Generated by scripts/local-env.sh from the local Supabase stack — do not commit.
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_KEY=${SERVICE_KEY}
SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
DATABASE_URL=postgres://api_user:postgres@127.0.0.1:54329/postgres
API_URL=http://localhost:8787
PLATFORM_HOST=tria.localhost
TENANT_DEMO_HOST=tria-demo.localhost
TENANT_LAB_HOST=tria-lab.localhost
ENV
