#!/usr/bin/env bash
# Prints an `.env.local` block for apps/api and apps/web from the running local Supabase stack.
# Usage: bash scripts/local-env.sh > apps/api/.env.local && bash scripts/local-env.sh > apps/web/.env.local
#        bash scripts/local-env.sh --write   # writes both files in one go (values never printed)
#
# The seed credentials below are LOCAL-STACK-ONLY throwaways, emitted so that a clean machine can run
# `pnpm supabase start` -> `pnpm db:reset` -> `bash scripts/local-env.sh --write` -> `pnpm db:seed`
# and then the whole suite, without having to discover from a stack trace that `pnpm db:seed`, the API
# integration suite and the platform e2e all require them (plan 01-06 made them mandatory; 01-08
# closed the gap). Export SEED_PASSWORD / SUPER_ADMIN_PASSWORD before running this script to override
# them; hosted environments get theirs from GitHub environment secrets and GCP Secret Manager and
# never from this file (see docs/DEPLOY.md).
set -euo pipefail
cd "$(dirname "$0")/.."

if [ "${1:-}" = "--write" ]; then
  for app in api web; do
    bash "$0" > "apps/$app/.env.local"
    echo "local-env: wrote apps/$app/.env.local" >&2
  done
  exit 0
fi

STATUS="$(pnpm --silent supabase status -o env)"

get() {
  printf '%s\n' "$STATUS" | grep -E "^$1=" | head -1 | cut -d= -f2- | tr -d '"'
}

SUPABASE_URL="$(get API_URL)"
SERVICE_KEY="$(get SERVICE_ROLE_KEY)"
[ -z "$SERVICE_KEY" ] && SERVICE_KEY="$(get SECRET_KEY)"
PUBLISHABLE_KEY="$(get ANON_KEY)"
[ -z "$PUBLISHABLE_KEY" ] && PUBLISHABLE_KEY="$(get PUBLISHABLE_KEY)"

if [ -z "$SUPABASE_URL" ] || [ -z "$SERVICE_KEY" ] || [ -z "$PUBLISHABLE_KEY" ]; then
  echo "local-env: could not read API_URL / service key / publishable key from 'supabase status -o env'" >&2
  exit 1
fi

cat <<ENV
# Generated by scripts/local-env.sh from the local Supabase stack — do not commit.
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_KEY=${SERVICE_KEY}
SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
# Local fallback (development only, recorded in 01-01-SUMMARY): the local Supavisor (54329) only knows its
# own pooler user (api_user -> ENOIDENTIFIER, api_user.rede-social -> ENOTFOUND), so api_user connects on
# the direct port. Hosted environments always use the transaction pooler URL from Secret Manager.
DATABASE_URL=postgres://api_user:postgres@127.0.0.1:54322/postgres
API_URL=http://localhost:8787
PLATFORM_HOST=tria.localhost
TENANT_DEMO_HOST=tria-demo.localhost
TENANT_LAB_HOST=tria-lab.localhost
# Local-stack-only seed credentials. Required by \`pnpm db:seed\`, apps/api's integration suite and
# apps/web's platform e2e; override by exporting them before running this script.
SEED_PASSWORD=${SEED_PASSWORD:-Segredo123}
SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL:-ferramentas@triacompany.com.br}
SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD:-SuperSegredo123}
ENV
