/**
 * Idempotent seed (D-14, D-17, D-19, D-24).
 * Run: `SEED_PASSWORD=... SUPER_ADMIN_PASSWORD=... pnpm db:seed`.
 *
 * Creates the seed tenants (tria-demo, tria-lab), one admin_tenant + one member each, their
 * `tenant_modules` rows and their primary, verified `tenant_domains` rows, plus TRIA's `super_admin`
 * in `platform_admins`. Safe to re-run. Passwords come from env only, never from git.
 */
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
// Type-only: erased at runtime, so it cannot pull a kernel module in before the env file is loaded.
import type { ModuleKey } from '@tria/contracts';

// Load the local stack values (generated by scripts/local-env.sh) before any kernel module reads env.
// Variables already present in the process environment take precedence over the file.
const envFile = resolve(process.cwd(), 'apps/api/.env.local');
if (existsSync(envFile)) process.loadEnvFile(envFile);

const { deriveBrandColors, normalizeHost, REAL_TENANT_DEFAULT_MODULES, TOGGLEABLE_MODULES } =
  await import('@tria/contracts');
const { and, eq, ne } = await import('drizzle-orm');
const { withAdminTx } = await import('@tria/core/db/admin-tx');
const {
  mediaAssets,
  memberProfiles,
  memberships,
  platformAdmins,
  tenantDomains,
  tenantModules,
  tenants,
} = await import('@tria/core/db/schema');
const { sqlClient } = await import('@tria/core/db');
const { supabaseAdmin } = await import('@tria/core/server/supabase-admin');
const { deriveIconSet } = await import('@tria/core/server/branding/icons');
const { uploadIconSet } = await import('@tria/core/server/platform/branding');
const { deriveVariants } = await import('@tria/core/server/media/variants');
const { putObject } = await import('@tria/core/server/media/storage');
const { mediaOriginalKey, mediaVariantKey } = await import('@tria/core/server/media/keys');
const { PURPOSE_WIDTHS } = await import('@tria/contracts/media');
const { sql } = await import('drizzle-orm');

/** The widths the worker derives for an avatar — the seed writes exactly the same ladder (R-06). */
const AVATAR_WIDTHS = PURPOSE_WIDTHS.avatar;

/**
 * D-28: both seed tenants carry a real favicon + PWA icon set derived from their seed logo at a FIXED
 * version: re-runs overwrite the same five objects (`uploadIconSet` upserts), so the seed stays
 * idempotent and never accumulates versions. No pg-boss job is enqueued — the seed is the fixture
 * writer of record; jobs belong to runtime mutations (02-13).
 */
const SEED_ICON_VERSION = 1;

const seedPassword = process.env.SEED_PASSWORD;
if (!seedPassword) {
  throw new Error(
    'SEED_PASSWORD is required (never stored in git); export it before running pnpm db:seed',
  );
}

// D-14: TRIA's platform admin. The e-mail has a default (it is not a secret); the password never does.
const SUPER_ADMIN_EMAIL = process.env.SUPER_ADMIN_EMAIL ?? 'ferramentas@triacompany.com.br';
const superAdminPassword = process.env.SUPER_ADMIN_PASSWORD;
if (!superAdminPassword) {
  throw new Error(
    'SUPER_ADMIN_PASSWORD is required (never stored in git); export it before running pnpm db:seed',
  );
}

const hostFromEnv = (name: string, fallback: string): string => {
  const value = normalizeHost(process.env[name] ?? fallback);
  if (!value) throw new Error(`${name} must be a non-empty hostname`);
  return value;
};
const PLATFORM_HOST = hostFromEnv('PLATFORM_HOST', 'tria.localhost');
const DEMO_HOST = hostFromEnv('TENANT_DEMO_HOST', 'tria-demo.localhost');
const LAB_HOST = hostFromEnv('TENANT_LAB_HOST', 'tria-lab.localhost');

// The platform host is configuration for apps/web (super_admin entry, D-21) — there is no platform tenant.
if (PLATFORM_HOST === DEMO_HOST || PLATFORM_HOST === LAB_HOST) {
  throw new Error(`PLATFORM_HOST (${PLATFORM_HOST}) must differ from the seed tenant hosts`);
}
if (DEMO_HOST === LAB_HOST) {
  throw new Error(`TENANT_DEMO_HOST and TENANT_LAB_HOST must differ (both are ${DEMO_HOST})`);
}

/**
 * A seeded community member (03-02, PROF-01/PROF-03). The names are FIXED and deliberately loaded
 * with pt-BR diacritics (`ç`, `ã`, `í`, `ñ`, `ü`, `'`), because `app.imm_unaccent` and the trigram
 * index are only honestly exercised by data that actually needs folding: 03-03's directory search
 * must find `João Gonçalves` from `goncal` and `Íris Muñoz` from `MUNOZ`.
 *
 * `bio: null` on purpose for two of them — 03-04's "sem bio" state and the D-02 nudge need members
 * who really lack a bio, not a screenshot of one.
 */
type SeedMember = {
  local: string;
  name: string;
  bio: string | null;
  /** A real `ready` avatar asset derived at seed time (03-01 broker shape, written directly). */
  photo?: { hex: string };
};

type SeedTenant = {
  slug: string;
  displayName: string;
  rulesText: string;
  host: string;
  /** Members beyond the tenant's admin and its original `member@<slug>.local`. */
  members: readonly SeedMember[];
  /** Exactly the keys enabled for this tenant; every other key is written with `enabled = false`. */
  modules: readonly ModuleKey[];
  /** D-25 source colors; the derivations are computed by `deriveBrandColors` at seed time. */
  colors: { primary: string; secondary: string };
  /** Root-relative wordmark served by apps/web (`public/seed-logos`); uploads are absolute URLs. */
  logoUrl: string;
};

const SEED_TENANTS: SeedTenant[] = [
  {
    slug: 'tria-demo',
    displayName: 'TRIA Demo',
    rulesText:
      'Regras da comunidade TRIA Demo: respeite as pessoas, não compartilhe conteúdo de terceiros sem autorização e use o chat de suporte para dúvidas.',
    host: DEMO_HOST,
    // D-17 all six + D-19: `example` (the throwaway module) is enabled HERE ONLY — never on a real
    // tenant, and never through REAL_TENANT_DEFAULT_MODULES, which must not contain it.
    modules: [...REAL_TENANT_DEFAULT_MODULES, 'example'],
    // Far from the neutral TRIA blue (#2e6fd0) and from tria-lab, so the brand smoke tells them apart.
    colors: { primary: '#7c3aed', secondary: '#a78bfa' },
    logoUrl: '/seed-logos/tria-demo.svg',
    members: [
      {
        local: 'joao.goncalves',
        name: 'João Gonçalves',
        bio: 'Organizo os encontros de sábado.',
        photo: { hex: '#7c3aed' },
      },
      {
        local: 'iris.munoz',
        name: 'Íris Muñoz',
        bio: 'Fotógrafa. Sempre com a câmera na mochila.',
        photo: { hex: '#0ea5e9' },
      },
      // No bio: the "sem bio" row and the D-02 nudge need a member who really has none.
      { local: 'ana.paula.ferreira', name: 'Ana Paula Ferreira', bio: null },
      { local: 'luis.angelo.sa', name: 'Luís Ângelo Sá', bio: 'Professor de história.' },
      { local: 'cristovao.nobrega', name: 'Cristóvão Nóbrega', bio: 'Curioso por natureza.' },
      { local: 'beatriz.almeida', name: 'Beatriz Almeida', bio: 'Corro aos domingos.' },
      // No bio either — two is enough to make "at least two" an honest assertion.
      { local: 'rafael.teixeira', name: 'Rafael Teixeira', bio: null },
      { local: 'sofia.davila', name: "Sofia D'Ávila", bio: 'Escrevo sobre a comunidade.' },
    ],
  },
  {
    slug: 'tria-lab',
    displayName: 'TRIA Lab',
    rulesText: 'Regras da comunidade TRIA Lab: ambiente de testes de isolamento entre tenants.',
    host: LAB_HOST,
    // D-17: only feed + events, so the isolation suite exercises the disabled-module 404 from Phase 1.
    modules: ['feed', 'events'],
    colors: { primary: '#0f766e', secondary: '#14b8a6' },
    logoUrl: '/seed-logos/tria-lab.svg',
    members: [
      { local: 'alvaro.pinheiro', name: 'Álvaro Pinheiro', bio: 'Testando o isolamento.' },
      { local: 'helena.kuster', name: 'Helena Küster', bio: 'Trago o café.' },
      { local: 'marcos.vinicius', name: 'Marcos Vinícius', bio: null },
    ],
  },
];

async function ensureUser(email: string, name: string, password: string): Promise<string> {
  const { data, error } = await supabaseAdmin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { name },
  });
  if (!error) return data.user.id;

  // Already exists (re-run): look it up. Small pilot, one page is enough.
  const { data: list, error: listError } = await supabaseAdmin.auth.admin.listUsers({
    perPage: 1000,
  });
  if (listError) throw listError;
  const existing = list.users.find((u) => u.email?.toLowerCase() === email.toLowerCase());
  if (!existing) throw error;
  return existing.id;
}

/**
 * The bio and (for two demo members) a REAL avatar asset, keyed by `membership_id` — the row itself
 * was already created by the trigger. Idempotent on both halves: the bio is an `update`, and the
 * avatar block short-circuits as soon as the profile already points at one, so a re-run never
 * accumulates assets or Storage objects.
 *
 * The avatar is written the way 02-13's seed writes the icon set: derived here and `putObject`-ed
 * under the broker's own key shape (`<tenant>/media/<assetId>/original` + one `w<width>.webp` per
 * avatar width), then recorded as a `ready` row. No pg-boss job is enqueued — the seed is the
 * fixture writer of record; jobs belong to runtime mutations.
 */
async function seedMemberProfile(
  tenantId: string,
  userId: string,
  member: SeedMember,
): Promise<boolean> {
  const existing = await withAdminTx(async (tx) =>
    tx
      .select({ id: memberProfiles.id, avatarAssetId: memberProfiles.avatarAssetId })
      .from(memberProfiles)
      .where(and(eq(memberProfiles.tenantId, tenantId), eq(memberProfiles.userId, userId)))
      .limit(1),
  );
  const profile = existing[0];
  if (!profile) throw new Error(`the membership trigger did not create a profile for ${userId}`);

  await withAdminTx(async (tx) => {
    await tx
      .update(memberProfiles)
      .set({ bio: member.bio, displayName: member.name, updatedAt: new Date() })
      .where(eq(memberProfiles.id, profile.id));
  });

  if (!member.photo || profile.avatarAssetId) return Boolean(profile.avatarAssetId);

  const assetId = crypto.randomUUID();
  const svg = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="640" viewBox="0 0 640 640"><rect width="640" height="640" fill="${member.photo.hex}"/><circle cx="320" cy="250" r="110" fill="#ffffff" fill-opacity="0.85"/><ellipse cx="320" cy="520" rx="190" ry="140" fill="#ffffff" fill-opacity="0.85"/></svg>`,
  );
  const widths = [...AVATAR_WIDTHS];
  const variants = await deriveVariants(svg, widths);
  const [original] = await deriveVariants(svg, [640]);
  if (!original) throw new Error('could not derive the seed avatar original');

  await putObject(mediaOriginalKey(tenantId, assetId), original.body, {
    contentType: 'image/webp',
  });
  for (const variant of variants) {
    await putObject(mediaVariantKey(tenantId, assetId, variant.width), variant.body, {
      contentType: 'image/webp',
    });
  }

  await withAdminTx(async (tx) => {
    await tx.insert(mediaAssets).values({
      id: assetId,
      tenantId,
      ownerUserId: userId,
      kind: 'image',
      purpose: 'avatar',
      status: 'ready',
      provider: 'supabase',
      mime: 'image/webp',
      bytes: original.body.length,
      width: 640,
      height: 640,
      variantWidths: widths,
      filename: 'avatar.webp',
      readyAt: new Date(),
    });
    await tx
      .update(memberProfiles)
      .set({ avatarAssetId: assetId, updatedAt: new Date() })
      .where(eq(memberProfiles.id, profile.id));
  });

  return true;
}

for (const t of SEED_TENANTS) {
  // D-25/D-28: the two source colors plus their persisted derivations and the root-relative logo.
  // The icon fields are NOT part of the upsert `set` (a re-run must never briefly null a live icon
  // set): the first insert starts them empty and the follow-up update below writes the derived set.
  const brandSource = { logoUrl: t.logoUrl, colors: deriveBrandColors(t.colors) };
  const tenantId = await withAdminTx(async (tx) => {
    const [tenant] = await tx
      .insert(tenants)
      .values({
        slug: t.slug,
        displayName: t.displayName,
        rulesText: t.rulesText,
        rulesVersion: 1,
        branding: { ...brandSource, faviconUrl: null, iconUrl: null },
      })
      .onConflictDoUpdate({
        target: tenants.slug,
        set: {
          displayName: t.displayName,
          rulesText: t.rulesText,
          branding: sql`${tenants.branding} || ${JSON.stringify(brandSource)}::jsonb`,
        },
      })
      .returning({ id: tenants.id });
    if (!tenant) throw new Error(`could not upsert tenant ${t.slug}`);
    return tenant.id;
  });

  // D-28: derive favicon + 192 + 512 + maskable-on-primary + apple-180 from the seed wordmark and
  // store them under `<tenant_id>/branding/icons/1/` in the public `branding` bucket, so the
  // per-tenant manifest (02-11) and the 02-16 smoke see real, distinct icons per host.
  const svg = await readFile(resolve(process.cwd(), 'apps/web/public/seed-logos', `${t.slug}.svg`));
  const set = await deriveIconSet(svg, { primaryHex: t.colors.primary, mime: 'image/svg+xml' });
  const { faviconUrl, iconUrls } = await uploadIconSet(tenantId, SEED_ICON_VERSION, set);
  await withAdminTx(async (tx) => {
    const iconPatch = JSON.stringify({ faviconUrl, iconUrls, iconVersion: SEED_ICON_VERSION });
    await tx
      .update(tenants)
      .set({ branding: sql`${tenants.branding} || ${iconPatch}::jsonb`, updatedAt: new Date() })
      .where(eq(tenants.id, tenantId));
  });
  console.log(`seed: tenant ${t.slug} icons derived (v${SEED_ICON_VERSION}) → ${iconUrls.i512}`);

  const people = [
    {
      role: 'admin_tenant' as const,
      email: `admin@${t.slug}.local`,
      name: `Admin ${t.displayName}`,
    },
    { role: 'member' as const, email: `member@${t.slug}.local`, name: `Membro ${t.displayName}` },
    // 03-02: a real community. The `member_profiles` row for each of these is created by the
    // `member_profiles_from_membership` trigger, with `display_name := users.name` — the seed never
    // inserts a profile row itself, which is exactly what makes the trigger's guarantee testable.
    ...t.members.map((m) => ({
      role: 'member' as const,
      email: `${m.local}@${t.slug}.local`,
      name: m.name,
      profile: m,
    })),
  ];
  let memberCount = 0;
  let photoCount = 0;
  for (const p of people) {
    const userId = await ensureUser(p.email, p.name, seedPassword);
    await withAdminTx(async (tx) => {
      await tx.insert(memberships).values({ tenantId, userId, role: p.role }).onConflictDoNothing();
    });
    if (p.role === 'member') memberCount += 1;
    if (!('profile' in p)) continue;
    if (await seedMemberProfile(tenantId, userId, p.profile)) photoCount += 1;
  }
  console.log(`seed: tenant ${t.slug} — ${memberCount} members, ${photoCount} with photo`);

  // D-16/D-17: one row per TOGGLEABLE key, so flipping a module later is an update, never an insert
  // race. A key absent from `t.modules` is written as `enabled = false` — indistinguishable from a
  // missing row for `requireModule`, but explicit in the platform panel.
  await withAdminTx(async (tx) => {
    for (const key of TOGGLEABLE_MODULES) {
      const enabled = t.modules.includes(key);
      await tx
        .insert(tenantModules)
        .values({ tenantId, moduleKey: key, enabled })
        .onConflictDoUpdate({
          target: [tenantModules.tenantId, tenantModules.moduleKey],
          set: { enabled, updatedAt: new Date() },
        });
    }
  });

  // D-24: ONE transaction — demote any other primary host first (a renamed TENANT_*_HOST on an
  // already-seeded database would otherwise create a second primary row and violate
  // tenant_domains_one_primary_per_tenant; the previous host stays as a non-primary alias).
  await withAdminTx(async (tx) => {
    await tx
      .update(tenantDomains)
      .set({ isPrimary: false })
      .where(
        and(
          eq(tenantDomains.tenantId, tenantId),
          ne(tenantDomains.host, t.host),
          eq(tenantDomains.isPrimary, true),
        ),
      );
    await tx
      .insert(tenantDomains)
      // D-36: seeded hosts are verified outright (verified_at is the resolution predicate) and
      // carry verification_status = 'verified' so the platform panel lists them as "Verificado".
      .values({
        tenantId,
        host: t.host,
        isPrimary: true,
        verifiedAt: new Date(),
        verificationStatus: 'verified',
      })
      .onConflictDoUpdate({
        target: tenantDomains.host,
        set: { tenantId, isPrimary: true, verifiedAt: new Date(), verificationStatus: 'verified' },
      });
  });

  console.log(
    `seed: tenant ${t.slug} (${t.displayName}) ready with admin + member and ${t.modules.length} module(s) on`,
  );
}

// D-14 / ROLE-01: TRIA's super_admin is an identity with NO membership — its authority is the
// `platform_admins` row alone, which only the admin lane behind `requireSuperAdmin()` can read.
const superAdminId = await ensureUser(SUPER_ADMIN_EMAIL, 'TRIA', superAdminPassword);
await withAdminTx(async (tx) => {
  await tx.insert(platformAdmins).values({ userId: superAdminId }).onConflictDoNothing();
});
console.log(`seed: platform admin ${SUPER_ADMIN_EMAIL} ready (no membership, by design)`);

console.log(`seed: hosts — platform=${PLATFORM_HOST} tria-demo=${DEMO_HOST} tria-lab=${LAB_HOST}`);
await sqlClient.end();
