/**
 * Idempotent seed (D-14, D-17, D-19, D-24).
 * Run: `SEED_PASSWORD=... SUPER_ADMIN_PASSWORD=... pnpm db:seed`.
 *
 * Creates the seed tenants (tria-demo, tria-lab), one admin_tenant + one member each, their
 * `tenant_modules` rows and their primary, verified `tenant_domains` rows, plus TRIA's `super_admin`
 * in `platform_admins`. Safe to re-run. Passwords come from env only, never from git.
 */
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
// Type-only: erased at runtime, so it cannot pull a kernel module in before the env file is loaded.
import type { ModuleKey } from '@tria/contracts';

// Load the local stack values (generated by scripts/local-env.sh) before any kernel module reads env.
// Variables already present in the process environment take precedence over the file.
const envFile = resolve(process.cwd(), 'apps/api/.env.local');
if (existsSync(envFile)) process.loadEnvFile(envFile);

const { deriveBrandColors, normalizeHost, REAL_TENANT_DEFAULT_MODULES, TOGGLEABLE_MODULES } =
  await import('@tria/contracts');
const { and, eq, ne } = await import('drizzle-orm');
const { withAdminTx } = await import('@tria/core/db/admin-tx');
const { memberships, platformAdmins, tenantDomains, tenantModules, tenants } = await import(
  '@tria/core/db/schema'
);
const { sqlClient } = await import('@tria/core/db');
const { supabaseAdmin } = await import('@tria/core/server/supabase-admin');

const seedPassword = process.env.SEED_PASSWORD;
if (!seedPassword) {
  throw new Error(
    'SEED_PASSWORD is required (never stored in git); export it before running pnpm db:seed',
  );
}

// D-14: TRIA's platform admin. The e-mail has a default (it is not a secret); the password never does.
const SUPER_ADMIN_EMAIL = process.env.SUPER_ADMIN_EMAIL ?? 'ferramentas@triacompany.com.br';
const superAdminPassword = process.env.SUPER_ADMIN_PASSWORD;
if (!superAdminPassword) {
  throw new Error(
    'SUPER_ADMIN_PASSWORD is required (never stored in git); export it before running pnpm db:seed',
  );
}

const hostFromEnv = (name: string, fallback: string): string => {
  const value = normalizeHost(process.env[name] ?? fallback);
  if (!value) throw new Error(`${name} must be a non-empty hostname`);
  return value;
};
const PLATFORM_HOST = hostFromEnv('PLATFORM_HOST', 'tria.localhost');
const DEMO_HOST = hostFromEnv('TENANT_DEMO_HOST', 'tria-demo.localhost');
const LAB_HOST = hostFromEnv('TENANT_LAB_HOST', 'tria-lab.localhost');

// The platform host is configuration for apps/web (super_admin entry, D-21) — there is no platform tenant.
if (PLATFORM_HOST === DEMO_HOST || PLATFORM_HOST === LAB_HOST) {
  throw new Error(`PLATFORM_HOST (${PLATFORM_HOST}) must differ from the seed tenant hosts`);
}
if (DEMO_HOST === LAB_HOST) {
  throw new Error(`TENANT_DEMO_HOST and TENANT_LAB_HOST must differ (both are ${DEMO_HOST})`);
}

type SeedTenant = {
  slug: string;
  displayName: string;
  rulesText: string;
  host: string;
  /** Exactly the keys enabled for this tenant; every other key is written with `enabled = false`. */
  modules: readonly ModuleKey[];
  /** D-25 source colors; the derivations are computed by `deriveBrandColors` at seed time. */
  colors: { primary: string; secondary: string };
  /** Root-relative wordmark served by apps/web (`public/seed-logos`); uploads are absolute URLs. */
  logoUrl: string;
};

const SEED_TENANTS: SeedTenant[] = [
  {
    slug: 'tria-demo',
    displayName: 'TRIA Demo',
    rulesText:
      'Regras da comunidade TRIA Demo: respeite as pessoas, não compartilhe conteúdo de terceiros sem autorização e use o chat de suporte para dúvidas.',
    host: DEMO_HOST,
    // D-17 all six + D-19: `example` (the throwaway module) is enabled HERE ONLY — never on a real
    // tenant, and never through REAL_TENANT_DEFAULT_MODULES, which must not contain it.
    modules: [...REAL_TENANT_DEFAULT_MODULES, 'example'],
    // Far from the neutral TRIA blue (#2e6fd0) and from tria-lab, so the brand smoke tells them apart.
    colors: { primary: '#7c3aed', secondary: '#a78bfa' },
    logoUrl: '/seed-logos/tria-demo.svg',
  },
  {
    slug: 'tria-lab',
    displayName: 'TRIA Lab',
    rulesText: 'Regras da comunidade TRIA Lab: ambiente de testes de isolamento entre tenants.',
    host: LAB_HOST,
    // D-17: only feed + events, so the isolation suite exercises the disabled-module 404 from Phase 1.
    modules: ['feed', 'events'],
    colors: { primary: '#0f766e', secondary: '#14b8a6' },
    logoUrl: '/seed-logos/tria-lab.svg',
  },
];

async function ensureUser(email: string, name: string, password: string): Promise<string> {
  const { data, error } = await supabaseAdmin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { name },
  });
  if (!error) return data.user.id;

  // Already exists (re-run): look it up. Small pilot, one page is enough.
  const { data: list, error: listError } = await supabaseAdmin.auth.admin.listUsers({
    perPage: 1000,
  });
  if (listError) throw listError;
  const existing = list.users.find((u) => u.email?.toLowerCase() === email.toLowerCase());
  if (!existing) throw error;
  return existing.id;
}

for (const t of SEED_TENANTS) {
  // D-25/D-28: the two source colors plus their persisted derivations; no icon set yet (02-11 derives it).
  const branding = {
    logoUrl: t.logoUrl,
    faviconUrl: null,
    iconUrl: null,
    iconUrls: null,
    iconVersion: 0,
    colors: deriveBrandColors(t.colors),
  };
  const tenantId = await withAdminTx(async (tx) => {
    const [tenant] = await tx
      .insert(tenants)
      .values({
        slug: t.slug,
        displayName: t.displayName,
        rulesText: t.rulesText,
        rulesVersion: 1,
        branding,
      })
      .onConflictDoUpdate({
        target: tenants.slug,
        set: { displayName: t.displayName, rulesText: t.rulesText, branding },
      })
      .returning({ id: tenants.id });
    if (!tenant) throw new Error(`could not upsert tenant ${t.slug}`);
    return tenant.id;
  });

  const people = [
    {
      role: 'admin_tenant' as const,
      email: `admin@${t.slug}.local`,
      name: `Admin ${t.displayName}`,
    },
    { role: 'member' as const, email: `member@${t.slug}.local`, name: `Membro ${t.displayName}` },
  ];
  for (const p of people) {
    const userId = await ensureUser(p.email, p.name, seedPassword);
    await withAdminTx(async (tx) => {
      await tx.insert(memberships).values({ tenantId, userId, role: p.role }).onConflictDoNothing();
    });
  }

  // D-16/D-17: one row per TOGGLEABLE key, so flipping a module later is an update, never an insert
  // race. A key absent from `t.modules` is written as `enabled = false` — indistinguishable from a
  // missing row for `requireModule`, but explicit in the platform panel.
  await withAdminTx(async (tx) => {
    for (const key of TOGGLEABLE_MODULES) {
      const enabled = t.modules.includes(key);
      await tx
        .insert(tenantModules)
        .values({ tenantId, moduleKey: key, enabled })
        .onConflictDoUpdate({
          target: [tenantModules.tenantId, tenantModules.moduleKey],
          set: { enabled, updatedAt: new Date() },
        });
    }
  });

  // D-24: ONE transaction — demote any other primary host first (a renamed TENANT_*_HOST on an
  // already-seeded database would otherwise create a second primary row and violate
  // tenant_domains_one_primary_per_tenant; the previous host stays as a non-primary alias).
  await withAdminTx(async (tx) => {
    await tx
      .update(tenantDomains)
      .set({ isPrimary: false })
      .where(
        and(
          eq(tenantDomains.tenantId, tenantId),
          ne(tenantDomains.host, t.host),
          eq(tenantDomains.isPrimary, true),
        ),
      );
    await tx
      .insert(tenantDomains)
      // D-36: seeded hosts are verified outright (verified_at is the resolution predicate) and
      // carry verification_status = 'verified' so the platform panel lists them as "Verificado".
      .values({
        tenantId,
        host: t.host,
        isPrimary: true,
        verifiedAt: new Date(),
        verificationStatus: 'verified',
      })
      .onConflictDoUpdate({
        target: tenantDomains.host,
        set: { tenantId, isPrimary: true, verifiedAt: new Date(), verificationStatus: 'verified' },
      });
  });

  console.log(
    `seed: tenant ${t.slug} (${t.displayName}) ready with admin + member and ${t.modules.length} module(s) on`,
  );
}

// D-14 / ROLE-01: TRIA's super_admin is an identity with NO membership — its authority is the
// `platform_admins` row alone, which only the admin lane behind `requireSuperAdmin()` can read.
const superAdminId = await ensureUser(SUPER_ADMIN_EMAIL, 'TRIA', superAdminPassword);
await withAdminTx(async (tx) => {
  await tx.insert(platformAdmins).values({ userId: superAdminId }).onConflictDoNothing();
});
console.log(`seed: platform admin ${SUPER_ADMIN_EMAIL} ready (no membership, by design)`);

console.log(`seed: hosts — platform=${PLATFORM_HOST} tria-demo=${DEMO_HOST} tria-lab=${LAB_HOST}`);
await sqlClient.end();
