import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

/**
 * Vitest config for the repo-level spikes (`pnpm spike:supavisor`).
 * Runs from the repository root: `vitest run --config scripts/vitest.config.ts`.
 *
 * Environment: process variables win; otherwise the spike-relevant keys are read from
 * `apps/api/.env.local` (generated by `scripts/local-env.sh`) when that file exists.
 * `DATABASE_URL` is deliberately NOT forwarded — the spike must try the transaction pooler
 * (`SPIKE_DATABASE_URL`, default port 54329) before any direct-port contingency.
 */
const SPIKE_KEYS = [
  'SPIKE_DATABASE_URL',
  'SPIKE_ADMIN_DATABASE_URL',
  'SPIKE_PROJECT_REF',
  'TENANT_A',
  'TENANT_B',
] as const;

function readEnvFile(): Record<string, string> {
  const file = fileURLToPath(new URL('../apps/api/.env.local', import.meta.url));
  if (!existsSync(file)) return {};
  const out: Record<string, string> = {};
  for (const raw of readFileSync(file, 'utf8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const fromFile = readEnvFile();
const env: Record<string, string> = {};
for (const key of SPIKE_KEYS) {
  const value = process.env[key] ?? fromFile[key];
  if (value) env[key] = value;
}

export default defineConfig({
  test: {
    environment: 'node',
    include: ['scripts/**/*.test.ts'],
    env,
    fileParallelism: false,
    testTimeout: 30_000,
    hookTimeout: 60_000,
  },
});
