-- story_comment_rules (05-07) — STORY-05 expressed as a fact the database cannot be talked out of,
-- and the closing of a latent three-valued CHECK hole Phase 4 left on the same constraint.
--
-- THE FILE IS TWO HALVES, the `20260923214059_stories.sql` shape one plan later:
--
--   1. GENERATED by `drizzle-kit generate` from `packages/modules/feed/db/schema.ts` — every
--      constraint, column and index below came out of the generator verbatim. `pnpm db:generate` is
--      a no-op against it, which is the property that keeps the TS schema and this folder honest.
--
--   2. HAND-ORDERED, plus two things the generator cannot know about: the BACKFILLS, and the story
--      branch of `app.feed_comment_count()`. The generator emitted the foreign key BEFORE the
--      unique constraints it references and the CHECKs before the data was made to satisfy them;
--      both orders fail. The statement order below is the one 05-RESEARCH §Code Examples 1 proved
--      against this project's Postgres 17.6 as a dry run on the REAL tables with their existing
--      rows, rolled back.
--
-- WHY A CONSTRAINT AND NOT A TRIGGER. A `before insert` trigger that read the parent row to decide
-- would be a read-then-write with no lock: two concurrent inserts could both observe a legal parent
-- and both succeed, producing exactly the row the rule forbids. A foreign key is enforced by an
-- index and cannot race, needs no `security definer` function and no `search_path` hardening. The
-- same reasoning `feed_comments_parent_fk` and `feed_post_media_kind_fk` already carry.
--
-- THE MECHANISM, in one paragraph. `feed_comments.target_kind` is a STORED GENERATED column —
-- `'post'` when the post target is present, `'story'` otherwise, which `feed_comments_target_chk`
-- makes total — so the row's TARGET becomes visible to a referential check. `unique (id, depth,
-- target_kind)` makes that triple nameable, and the self foreign key is widened to three columns,
-- so the only parent a reply may name is `(parent, 0, 'post')`. A story comment's triple is
-- `(id, 0, 'story')`: there is no legal value of `parent_target_kind` that finds it. The like half
-- is the same technique with two columns — `unique (id, target_kind)` and
-- `feed_likes_comment_fk (comment_id, comment_target_kind)`.
--
-- Each refusal fails BOTH honestly and while lying, and `supabase/tests/110-communities-stories.sql`
-- asserts both paths with their positive controls:
--   * reply naming `parent_target_kind = 'story'`  -> 23514 on feed_comments_parent_shape_chk
--   * reply naming `parent_target_kind = 'post'`   -> 23503 on feed_comments_parent_fk
--   * like naming `comment_target_kind = 'story'`  -> 23514 on feed_likes_comment_kind_chk
--   * like naming `comment_target_kind = 'post'`   -> 23503 on feed_likes_comment_fk
--
-- WHY EVERY EQUALITY IN BOTH CHECKS IS GUARDED BY AN EXPLICIT `is not null` (PITFALL 1 and 2, and
-- the reason the two constraints are written together in one migration). SQL is three-valued: a
-- CHECK passes unless it evaluates to FALSE, so a branch containing an unguarded equality against a
-- nullable column evaluates to NULL and is SATISFIED. Phase 4's
-- `(parent_id is not null and parent_depth = 0 and depth = 1)` was exactly that: with a NULL
-- `parent_depth` it read `true AND NULL AND true` = NULL and the row INSERTED — verified against
-- this project's real `feed_comments` table, rolled back. The composite foreign key did not save it
-- either, because MATCH SIMPLE does not enforce a composite key when ANY of its columns is null. So
-- the FOREIGN KEY ALONE IS NOT SUFFICIENT and the CHECK ALONE IS NOT SUFFICIENT: they are one
-- mechanism, and the probe that inserts today is asserted to fail after, in BOTH
-- `supabase/tests/090-feed.sql` (the Phase 4 file, where the hole lived) and
-- `supabase/tests/110-communities-stories.sql`.
--
-- WHY THE BACKFILLS RUN BEFORE THE CONSTRAINTS AND WHAT THEY ASSUME. `'post'` is correct for every
-- existing row because NO STORY COMMENT EXISTS YET: `feed_comments.story_id` got its foreign key in
-- 05-05 and nothing has ever written it, and `feed_likes.comment_id` has only ever pointed at post
-- comments. Run in the other order, the existing replies and comment likes would fail validation
-- and the migration would abort.
--
-- WHY THIS MIGRATION IS NOT THE TRIVIAL ONE 05-05's HEADER PROMISED ITS SUCCESSOR WOULD NOT BE.
-- Adding a STORED GENERATED column REWRITES the table: `feed_comments` and `feed_likes` are both
-- rewritten here, under an `ACCESS EXCLUSIVE` lock, and the two new foreign keys then scan the
-- child rows to validate. At pilot volume this is milliseconds and the research ran the whole
-- sequence against the real tables and their rows. At millions of rows it would need staging — add
-- the column and the discriminators, backfill in batches, add the constraints `NOT VALID`, then
-- `VALIDATE CONSTRAINT` under a weaker lock. Recorded here rather than discovered later (T-05-46).

-- ── 1. drop the Phase 4 constraints, dependents first ──────────────────────────────────────────
-- The foreign key depends on `feed_comments_id_depth_uq`, so the unique cannot go first; the
-- generator emitted them in the opposite order and that order fails.
ALTER TABLE "feed_comments" DROP CONSTRAINT "feed_comments_parent_fk";--> statement-breakpoint
ALTER TABLE "feed_comments" DROP CONSTRAINT "feed_comments_parent_shape_chk";--> statement-breakpoint
ALTER TABLE "feed_comments" DROP CONSTRAINT "feed_comments_id_depth_uq";--> statement-breakpoint

-- ── 2. the discriminator and the two redundant columns ─────────────────────────────────────────
ALTER TABLE "feed_comments" ADD COLUMN "target_kind" text GENERATED ALWAYS AS (case when post_id is not null then 'post' else 'story' end) STORED;--> statement-breakpoint
ALTER TABLE "feed_comments" ADD COLUMN "parent_target_kind" text;--> statement-breakpoint
ALTER TABLE "feed_likes" ADD COLUMN "comment_target_kind" text;--> statement-breakpoint

-- ── 3. BACKFILL, before anything validates ─────────────────────────────────────────────────────
-- `'post'` for every comment that has a parent and every like that has a comment target. Correct
-- because no story comment exists yet — see the header.
UPDATE public.feed_comments SET parent_target_kind = 'post' WHERE parent_id IS NOT NULL;--> statement-breakpoint
UPDATE public.feed_likes SET comment_target_kind = 'post' WHERE comment_id IS NOT NULL;--> statement-breakpoint

-- ── 4. the nameable targets ────────────────────────────────────────────────────────────────────
-- Both are logically redundant — `id` is already the primary key — and both exist ONLY so a child
-- row can name a triple / a pair in a single referential check.
ALTER TABLE "feed_comments" ADD CONSTRAINT "feed_comments_id_depth_kind_uq" UNIQUE("id","depth","target_kind");--> statement-breakpoint
ALTER TABLE "feed_comments" ADD CONSTRAINT "feed_comments_id_kind_uq" UNIQUE("id","target_kind");--> statement-breakpoint

-- ── 5. the two composite foreign keys ──────────────────────────────────────────────────────────
ALTER TABLE "feed_comments" ADD CONSTRAINT "feed_comments_parent_fk" FOREIGN KEY ("parent_id","parent_depth","parent_target_kind") REFERENCES "public"."feed_comments"("id","depth","target_kind") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feed_likes" ADD CONSTRAINT "feed_likes_comment_fk" FOREIGN KEY ("comment_id","comment_target_kind") REFERENCES "public"."feed_comments"("id","target_kind") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

-- ── 6. the two rewritten CHECKs, every equality null-guarded ───────────────────────────────────
ALTER TABLE "feed_comments" ADD CONSTRAINT "feed_comments_parent_shape_chk" CHECK ((parent_id is null and parent_depth is null and parent_target_kind is null and depth = 0)
       or (parent_id is not null
           and parent_depth is not null and parent_depth = 0
           and parent_target_kind is not null and parent_target_kind = 'post'
           and depth = 1));--> statement-breakpoint
ALTER TABLE "feed_likes" ADD CONSTRAINT "feed_likes_comment_kind_chk" CHECK ((comment_id is null and comment_target_kind is null)
       or (comment_id is not null
           and comment_target_kind is not null and comment_target_kind = 'post'));--> statement-breakpoint

-- ── 7. D-83's ascending index ──────────────────────────────────────────────────────────────────
-- A story's comments are one FLAT conversation, so they run forward in time; a post's root comments
-- run backward because that list is a ranking of threads. Serving `asc` from the existing
-- `DESC NULLS FIRST` index is a backward scan, and the keyset comparison the cursor envelope
-- carries (`<` for desc, `>` for asc) cannot page one — page 2 would silently repeat or skip rows.
-- One index, one direction, one comparison (Pitfall 8). Pinned BY NAME in the pgTAP EXPLAIN block.
CREATE INDEX "feed_comments_tenant_story_root_asc_idx" ON "feed_comments" USING btree ("tenant_id","story_id","created_at","id") WHERE parent_id is null and deleted_at is null;--> statement-breakpoint

-- ── 8. the comment counter's STORY branch ──────────────────────────────────────────────────────
-- THE SAME FUNCTION, REPLACED — not a second trigger, exactly as `20260923234657_story_like_counters.sql`
-- filled the like counter's reserved slot. There is still one trigger on `public.feed_comments`
-- (`feed_comments_count`, created by `20260922162449_feed_counters.sql` and untouched here) and
-- therefore one writer of every comment counter in the product. Two triggers would fire in NAME
-- order rather than in a stated order, and a reader asking "what writes stories.comment_count?"
-- would have to find both.
--
-- The posture is copied verbatim and deliberately: `language plpgsql set search_path = ''`, fully
-- qualified names, NO `security definer`. The function runs on the writer's own comment row inside
-- the writer's own tenant lane against a table whose isolation policy the writer already satisfies,
-- so it needs no elevated right and gets none — an elevated trigger here would be a standing way to
-- move another tenant's counter.
--
-- The soft delete is an UPDATE, not a DELETE (Pitfall 5/10), so the UPDATE arm branches on the
-- TRANSITION of `deleted_at`: a removed comment moves the number exactly once, a restore moves it
-- back, and every other update of the column changes nothing. There is no `greatest(0, …)` clamp,
-- precisely so the pgTAP reconciliation can go red instead of hiding drift (T-05-47).
create or replace function app.feed_comment_count() returns trigger
  language plpgsql set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    if new.post_id is not null and new.deleted_at is null then
      update public.feed_posts set comment_count = comment_count + 1 where id = new.post_id;
    elsif new.story_id is not null and new.deleted_at is null then
      update public.stories set comment_count = comment_count + 1 where id = new.story_id;
    end if;
  elsif tg_op = 'DELETE' then
    if old.post_id is not null and old.deleted_at is null then
      update public.feed_posts set comment_count = comment_count - 1 where id = old.post_id;
    elsif old.story_id is not null and old.deleted_at is null then
      update public.stories set comment_count = comment_count - 1 where id = old.story_id;
    end if;
  elsif tg_op = 'UPDATE' then
    if new.post_id is not null then
      if old.deleted_at is null and new.deleted_at is not null then
        -- the D-61 soft delete: the row stays for Phase 8 moderation, the count does not
        update public.feed_posts set comment_count = comment_count - 1 where id = new.post_id;
      elsif old.deleted_at is not null and new.deleted_at is null then
        -- a Phase 8 restore; every other update of deleted_at changes nothing
        update public.feed_posts set comment_count = comment_count + 1 where id = new.post_id;
      end if;
    elsif new.story_id is not null then
      if old.deleted_at is null and new.deleted_at is not null then
        update public.stories set comment_count = comment_count - 1 where id = new.story_id;
      elsif old.deleted_at is not null and new.deleted_at is null then
        update public.stories set comment_count = comment_count + 1 where id = new.story_id;
      end if;
    end if;
  end if;
  return null;
end
$$;--> statement-breakpoint

-- The grant is re-stated because it costs nothing and keeps the file idempotent; the roles are the
-- same three `20260922162449_feed_counters.sql` granted.
grant execute on function app.feed_comment_count() to authenticated, service_role, api_user;--> statement-breakpoint

-- BACKFILL, once: every story comment that landed before this branch existed adjusted nothing. There
-- are none in any environment today (the column has never had a writer), but a backfill that is
-- correct at any volume is the same four lines as one that assumes zero — the `story_like_counters`
-- rule restated.
update public.stories s
   set comment_count = coalesce(counted.n, 0)
  from (select story_id, count(*)::int as n
          from public.feed_comments
         where story_id is not null and deleted_at is null
         group by story_id) counted
 where counted.story_id = s.id
   and s.comment_count is distinct from counted.n;
