-- story_highlights (05.2-01) — HIGHLIGHT-01/02/05: named highlights that belong to one PLACE (Início
-- or one community), and the copy of every existing pin into one of them.
--
-- THE FILE IS TWO HALVES, the `20260924022607_story_community_pins.sql` shape:
--
--   1. GENERATED by `drizzle-kit generate --name=story_highlights` from
--      `packages/modules/stories/db/schema.ts` — everything down to the
--      `story_highlights_tenant_isolation` policy, byte for byte. `pnpm db:generate` is a no-op
--      against it, which is the property that keeps the TS schema and this folder honest. The
--      generate is CREATE-ONLY on purpose: `story_community_pins` is still in the schema, because a
--      single generate that both creates and drops tables prompts "created or renamed?" and orders
--      the DROP before anything could copy the pins (05.2 RESEARCH Pattern 2, Pitfall 1). Plan 11's
--      own drop-only file retires the pins table after this one has copied it.
--
--   2. HAND-WRITTEN — three statements:
--
--      a. `story_highlights_community_fk`. It is not generated because it CANNOT be: the
--         communities table belongs to `@rede-social/module-communities`, and `turbo.json`'s boundary
--         allowlist denies a `module -> module` package dependency (MOD-02). The DATABASE enforces
--         it either way, and `120-story-highlights.sql` asserts it (23503 + positive control).
--         `community_id` NULL means Início, and a NULL passes a foreign key by definition.
--
--      b. THE BACKFILL: ONE data-modifying CTE that creates one highlight titled `Destaques` at
--         position 0 per (tenant, community) that HAS pins, and copies every pin into an item of
--         the highlight created for ITS OWN (tenant, community) pair — `added_by_user_id` =
--         `pinned_by_user_id`, `added_at` = `pinned_at`. A story pinned to two communities
--         therefore becomes two items under two highlights, never one merged row. A tenant or
--         community with zero pins gets no highlight at all (the CTE groups over existing pins
--         only), so a fresh `db reset` — where the seed runs AFTER migrations — migrates zero rows.
--
--      c. THE GUARD: a `DO` block that RAISES when any pin has no matching item, or any
--         community's item count differs from its pin count. The Supabase CLI applies one
--         migration file atomically (verified on CLI 2.117: a probe that raised left neither its
--         table nor a `schema_migrations` row), so a tripped guard aborts the WHOLE file — the
--         tables included — rather than let an environment lose a pin.
--
-- WHY THE BACKFILL AND ITS GUARD LIVE IN THIS FILE and not in a `--custom` one: the copy is only
-- meaningful in the same transaction as the tables it fills. Split into a second file, a failed
-- copy would leave empty highlight tables committed beside the pins, and the drop that plan 11
-- ships could then run against a database whose copy never happened.
--
-- WHY THE COVER STAYS NULL IN THE BACKFILL: the cover is resolved at READ time (R-D-D). With no
-- chosen cover, the rule falls to "the most recently ADDED live image item", and for a migrated
-- highlight `added_at = pinned_at` — so the read already yields the most recently pinned story as
-- the cover (D-116) without this file choosing one.
--
-- WHY PLAY ORDER IS NOT A BACKFILL CONCERN: items carry no ordering column (D-103). A highlight
-- plays by the STORY's `published_at`, so two pins with equal `pinned_at` cannot change the order.
--
-- WHY THE FOREIGN KEY IS VALIDATING AND NOT `NOT VALID`: the table is created in this same file and
-- holds only the rows the backfill wrote from pins whose community FK was already enforced.
--
-- ── GENERATED (half 1) ─────────────────────────────────────────────────────────────────────────
CREATE TABLE "story_highlight_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"highlight_id" uuid NOT NULL,
	"story_id" uuid NOT NULL,
	"added_by_user_id" uuid NOT NULL,
	"added_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "story_highlight_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "story_highlights" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"community_id" uuid,
	"title" text NOT NULL,
	"position" integer NOT NULL,
	"cover_story_id" uuid,
	"cover_asset_id" uuid,
	"created_by_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "story_highlights_title_chk" CHECK (char_length("story_highlights"."title") between 1 and 15 and "story_highlights"."title" = btrim("story_highlights"."title")),
	CONSTRAINT "story_highlights_cover_chk" CHECK (num_nonnulls("story_highlights"."cover_story_id", "story_highlights"."cover_asset_id") <= 1),
	CONSTRAINT "story_highlights_position_chk" CHECK ("story_highlights"."position" >= 0)
);
--> statement-breakpoint
ALTER TABLE "story_highlights" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "story_highlight_items" ADD CONSTRAINT "story_highlight_items_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_highlight_items" ADD CONSTRAINT "story_highlight_items_highlight_id_story_highlights_id_fk" FOREIGN KEY ("highlight_id") REFERENCES "public"."story_highlights"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_highlight_items" ADD CONSTRAINT "story_highlight_items_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_highlight_items" ADD CONSTRAINT "story_highlight_items_added_by_user_id_users_id_fk" FOREIGN KEY ("added_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_highlights" ADD CONSTRAINT "story_highlights_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_highlights" ADD CONSTRAINT "story_highlights_cover_story_id_stories_id_fk" FOREIGN KEY ("cover_story_id") REFERENCES "public"."stories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_highlights" ADD CONSTRAINT "story_highlights_cover_asset_id_media_assets_id_fk" FOREIGN KEY ("cover_asset_id") REFERENCES "public"."media_assets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_highlights" ADD CONSTRAINT "story_highlights_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "story_highlight_items_uq" ON "story_highlight_items" USING btree ("highlight_id","story_id");--> statement-breakpoint
CREATE INDEX "story_highlight_items_tenant_story_idx" ON "story_highlight_items" USING btree ("tenant_id","story_id");--> statement-breakpoint
CREATE INDEX "story_highlights_tenant_place_idx" ON "story_highlights" USING btree ("tenant_id","community_id","position","id");--> statement-breakpoint
CREATE POLICY "story_highlight_items_tenant_isolation" ON "story_highlight_items" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id()) WITH CHECK (tenant_id = app.tenant_id());--> statement-breakpoint
CREATE POLICY "story_highlights_tenant_isolation" ON "story_highlights" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id()) WITH CHECK (tenant_id = app.tenant_id());
--> statement-breakpoint
-- ── HAND-WRITTEN (half 2) ──────────────────────────────────────────────────────────────────────
-- (a) `on delete cascade`: archiving is what the product offers, but if a tenant row ever cascades
-- through a community, a highlight pointing at a container that no longer exists would be a row no
-- read could ever explain. Its items go with it through `story_highlight_items`' own cascade.
ALTER TABLE "story_highlights" ADD CONSTRAINT "story_highlights_community_fk" FOREIGN KEY ("community_id") REFERENCES "public"."communities"("id") ON DELETE cascade;
--> statement-breakpoint
-- (b) THE BACKFILL — ONE data-modifying CTE: every item joins the highlight created for ITS OWN
-- (tenant, community) pair, never a title match. `first_pinner` is the curator of the first pin, and
-- the highlight's `created_at` / `updated_at` span the first and last pin of its community.
with pinned as (
  select p.tenant_id, p.community_id,
         min(p.pinned_at) as first_pinned_at,
         max(p.pinned_at) as last_pinned_at,
         (array_agg(p.pinned_by_user_id order by p.pinned_at, p.id))[1] as first_pinner
    from public.story_community_pins p
   group by p.tenant_id, p.community_id
), created as (
  insert into public.story_highlights
    (tenant_id, community_id, title, position, created_by_user_id, created_at, updated_at)
  select tenant_id, community_id, 'Destaques', 0, first_pinner, first_pinned_at, last_pinned_at
    from pinned
  returning id, tenant_id, community_id
)
insert into public.story_highlight_items (tenant_id, highlight_id, story_id, added_by_user_id, added_at)
select p.tenant_id, c.id, p.story_id, p.pinned_by_user_id, p.pinned_at
  from public.story_community_pins p
  join created c on c.tenant_id = p.tenant_id and c.community_id = p.community_id;
--> statement-breakpoint
-- (c) THE GUARD: abort the whole file (atomic, verified on CLI 2.117) rather than lose a pin. Two
-- independent checks — a pin with no identical item under its own community's highlight, and a
-- (tenant, community) whose item count differs from its pin count — and the exception names both.
do $$
declare
  v_missing int;
  v_mismatch int;
begin
  select count(*) into v_missing
    from public.story_community_pins p
   where not exists (
     select 1
       from public.story_highlight_items i
       join public.story_highlights h on h.id = i.highlight_id
      where i.story_id = p.story_id
        and h.community_id = p.community_id
        and h.tenant_id = p.tenant_id
        and i.tenant_id = p.tenant_id
        and i.added_at = p.pinned_at
        and i.added_by_user_id = p.pinned_by_user_id);

  select count(*) into v_mismatch
    from (
      select tenant_id, community_id, count(*) as n
        from public.story_community_pins
       group by 1, 2) a
    full join (
      select h.tenant_id, h.community_id, count(*) as n
        from public.story_highlight_items i
        join public.story_highlights h on h.id = i.highlight_id
       group by 1, 2) b using (tenant_id, community_id)
   where a.n is distinct from b.n;

  if v_missing > 0 or v_mismatch > 0 then
    raise exception 'story_highlights backfill would lose pins: % missing, % communities mismatched',
      v_missing, v_mismatch;
  end if;
end $$;
