-- store (08.2-01, STORE-01, STORE-02, STORE-08, STORE-11, STORE-20; D-354, D-356, D-361) — the store
-- module's four tables, the feed's community gate policy and the `store` module key. GENERATED by
-- drizzle-kit from packages/modules/store/db/schema.ts, packages/modules/feed/db/schema.ts and
-- packages/contracts/src/modules.ts; every statement below is drizzle-kit's, unchanged:
--
--   1. the four tables with their CHECKs, RLS enabled on each:
--      - `store_products` (price in integer cents, `active | archived`),
--      - `store_product_communities` (which product opens which community; its FK to `communities`
--        is hand SQL in the later `*_store_functions.sql`, MOD-02),
--      - `store_orders` (the purchase ledger; `amount_cents`/`currency` are a snapshot, D-361),
--      - `store_entitlements` (who holds which product; purchase XOR grant);
--   2. drop `tenant_modules_key_chk`, then (after the FKs and indexes) recreate it ending in 'store'.
--      It is GENERATED from `TOGGLEABLE_MODULES`, so appending the key there is what produced it;
--   3. the foreign keys (tenant FKs `on delete cascade`; links cascade with their product);
--   4. the indexes, every one tenant-first (pgTAP 040), including the two partial unique ARBITERS
--      `store_orders_live_uq` and `store_entitlements_active_uq` that `app.store_purchase` inserts
--      against with `on conflict … do nothing` (T-08.2-05);
--   5. the policies:
--      - `feed_posts_community_gate`, AS RESTRICTIVE (it ANDs with `feed_posts_tenant_isolation`; a
--        permissive one would widen access). It calls `app.community_locked_ids()` (the kernel stub
--        from `*_community_gate_seam.sql`, which sorts BEFORE this file, RESEARCH Pitfall 2) and
--        `app.feed_sample_post_ids()` (from `*_feed_community_sample.sql`, also before this file);
--      - `store_orders_select_own_or_admin` and `store_entitlements_select_own_or_admin`: SELECT
--        only, and NO insert/update/delete policy (STORE-20, T-08.2-03, the `memberships`
--        precedent); writes go through SECURITY DEFINER functions only;
--      - the standard isolation policy on `store_products` and `store_product_communities`.
--
-- NO BACKFILL (unlike `reels_module`): there is no insert into `tenant_modules`. A missing row reads
-- as disabled, which is the store's default (STORE-01), so for every existing tenant this migration
-- changes nothing a member can observe: with no product linked, every gate function answers '{}'.
-- Expand-only: safe to apply before the API revision that calls these objects (Pitfall 11).

CREATE TABLE "store_entitlements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"source" text NOT NULL,
	"order_id" uuid,
	"granted_by_user_id" uuid,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoked_by_user_id" uuid,
	"expires_at" timestamp with time zone,
	CONSTRAINT "store_entitlements_source_chk" CHECK ("store_entitlements"."source" in ('purchase','grant')),
	CONSTRAINT "store_entitlements_status_chk" CHECK ("store_entitlements"."status" in ('active','revoked')),
	CONSTRAINT "store_entitlements_source_order_chk" CHECK (("store_entitlements"."source" = 'purchase') = ("store_entitlements"."order_id" is not null)),
	CONSTRAINT "store_entitlements_source_grant_chk" CHECK (("store_entitlements"."source" = 'grant') = ("store_entitlements"."granted_by_user_id" is not null))
);
--> statement-breakpoint
ALTER TABLE "store_entitlements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "store_orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"status" text NOT NULL,
	"amount_cents" integer NOT NULL,
	"currency" text NOT NULL,
	"provider" text DEFAULT 'none' NOT NULL,
	"provider_ref" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"paid_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"revoked_by_user_id" uuid,
	CONSTRAINT "store_orders_status_chk" CHECK ("store_orders"."status" in ('pending','paid','revoked')),
	CONSTRAINT "store_orders_amount_chk" CHECK ("store_orders"."amount_cents" >= 0),
	CONSTRAINT "store_orders_currency_chk" CHECK ("store_orders"."currency" in ('BRL')),
	CONSTRAINT "store_orders_provider_chk" CHECK ("store_orders"."provider" in ('none'))
);
--> statement-breakpoint
ALTER TABLE "store_orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "store_product_communities" (
	"tenant_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"community_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "store_product_communities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "store_products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_by_user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"image_asset_id" uuid,
	"price_cents" integer NOT NULL,
	"currency" text DEFAULT 'BRL' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "store_products_price_chk" CHECK ("store_products"."price_cents" between 0 and 10000000),
	CONSTRAINT "store_products_currency_chk" CHECK ("store_products"."currency" in ('BRL')),
	CONSTRAINT "store_products_status_chk" CHECK ("store_products"."status" in ('active','archived'))
);
--> statement-breakpoint
ALTER TABLE "store_products" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tenant_modules" DROP CONSTRAINT "tenant_modules_key_chk";--> statement-breakpoint
ALTER TABLE "store_entitlements" ADD CONSTRAINT "store_entitlements_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_entitlements" ADD CONSTRAINT "store_entitlements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_entitlements" ADD CONSTRAINT "store_entitlements_product_id_store_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."store_products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_entitlements" ADD CONSTRAINT "store_entitlements_order_id_store_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."store_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_entitlements" ADD CONSTRAINT "store_entitlements_granted_by_user_id_users_id_fk" FOREIGN KEY ("granted_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_entitlements" ADD CONSTRAINT "store_entitlements_revoked_by_user_id_users_id_fk" FOREIGN KEY ("revoked_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_orders" ADD CONSTRAINT "store_orders_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_orders" ADD CONSTRAINT "store_orders_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_orders" ADD CONSTRAINT "store_orders_product_id_store_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."store_products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_orders" ADD CONSTRAINT "store_orders_revoked_by_user_id_users_id_fk" FOREIGN KEY ("revoked_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_product_communities" ADD CONSTRAINT "store_product_communities_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_product_communities" ADD CONSTRAINT "store_product_communities_product_id_store_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."store_products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_products" ADD CONSTRAINT "store_products_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_products" ADD CONSTRAINT "store_products_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_products" ADD CONSTRAINT "store_products_image_asset_id_media_assets_id_fk" FOREIGN KEY ("image_asset_id") REFERENCES "public"."media_assets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "store_entitlements_active_uq" ON "store_entitlements" USING btree ("tenant_id","user_id","product_id") WHERE status = 'active';--> statement-breakpoint
CREATE INDEX "store_entitlements_tenant_user_status_idx" ON "store_entitlements" USING btree ("tenant_id","user_id","status");--> statement-breakpoint
CREATE INDEX "store_entitlements_tenant_product_created_idx" ON "store_entitlements" USING btree ("tenant_id","product_id","created_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE UNIQUE INDEX "store_orders_live_uq" ON "store_orders" USING btree ("tenant_id","user_id","product_id") WHERE status in ('pending','paid');--> statement-breakpoint
CREATE INDEX "store_orders_tenant_user_idx" ON "store_orders" USING btree ("tenant_id","user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "store_product_communities_uq" ON "store_product_communities" USING btree ("tenant_id","product_id","community_id");--> statement-breakpoint
CREATE INDEX "store_product_communities_tenant_community_idx" ON "store_product_communities" USING btree ("tenant_id","community_id");--> statement-breakpoint
CREATE INDEX "store_products_tenant_created_idx" ON "store_products" USING btree ("tenant_id","created_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
ALTER TABLE "tenant_modules" ADD CONSTRAINT "tenant_modules_key_chk" CHECK ("tenant_modules"."module_key" in ('feed','communities','stories','events','chat','notifications','reels','store'));--> statement-breakpoint
CREATE POLICY "feed_posts_community_gate" ON "feed_posts" AS RESTRICTIVE FOR SELECT TO "authenticated" USING (community_id is null or community_id <> all (coalesce((select app.community_locked_ids()), '{}'::uuid[])) or id = any (coalesce((select app.feed_sample_post_ids()), '{}'::uuid[])));--> statement-breakpoint
CREATE POLICY "store_entitlements_select_own_or_admin" ON "store_entitlements" AS PERMISSIVE FOR SELECT TO "authenticated" USING (tenant_id = app.tenant_id() and (user_id = app.user_id() or app.tenant_role() = 'admin_tenant'));--> statement-breakpoint
CREATE POLICY "store_orders_select_own_or_admin" ON "store_orders" AS PERMISSIVE FOR SELECT TO "authenticated" USING (tenant_id = app.tenant_id() and (user_id = app.user_id() or app.tenant_role() = 'admin_tenant'));--> statement-breakpoint
CREATE POLICY "store_product_communities_tenant_isolation" ON "store_product_communities" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id()) WITH CHECK (tenant_id = app.tenant_id());--> statement-breakpoint
CREATE POLICY "store_products_tenant_isolation" ON "store_products" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id()) WITH CHECK (tenant_id = app.tenant_id());