-- event_attendances (06-03) — EVENT-03's attendance row (D-216): one row per member per event, with
-- the RSVP answer and, later, the check-in. GENERATED by `drizzle-kit generate` from
-- `packages/modules/events/db/schema.ts`, byte for byte below this header, so `pnpm db:generate`
-- stays a no-op. What drizzle-kit cannot model (the guard trigger that refuses a write the event no
-- longer allows, for every writer) is `20260927154335_event_attendance_guard.sql`.
--
-- The select policy is tenant-wide (the in-lane counts need every row of the event); the two write
-- policies admit only the caller's OWN `going`/`not_going` row, so `checked_in` and `walk_in` are
-- unreachable from a member lane (T-06-11). There is NO delete policy: answers and check-ins always
-- survive (D-214). Proved by `supabase/tests/141-event-attendances.sql`.

CREATE TABLE "event_attendances" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"status" text NOT NULL,
	"responded_at" timestamp with time zone,
	"checked_in_at" timestamp with time zone,
	"checkin_via" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event_attendances_status_chk" CHECK ("event_attendances"."status" in ('going','not_going','checked_in','walk_in')),
	CONSTRAINT "event_attendances_checkin_chk" CHECK (("event_attendances"."status" in ('checked_in','walk_in')) = ("event_attendances"."checked_in_at" is not null) and ("event_attendances"."status" in ('checked_in','walk_in')) = ("event_attendances"."checkin_via" is not null)),
	CONSTRAINT "event_attendances_via_chk" CHECK ("event_attendances"."checkin_via" is null or "event_attendances"."checkin_via" in ('code','online')),
	CONSTRAINT "event_attendances_answered_chk" CHECK ("event_attendances"."status" = 'walk_in' or "event_attendances"."responded_at" is not null)
);
--> statement-breakpoint
ALTER TABLE "event_attendances" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "event_attendances" ADD CONSTRAINT "event_attendances_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_attendances" ADD CONSTRAINT "event_attendances_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_attendances" ADD CONSTRAINT "event_attendances_event_fk" FOREIGN KEY ("tenant_id","event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "event_attendances_tenant_event_user_uq" ON "event_attendances" USING btree ("tenant_id","event_id","user_id");--> statement-breakpoint
CREATE INDEX "event_attendances_tenant_event_status_idx" ON "event_attendances" USING btree ("tenant_id","event_id","status","responded_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "event_attendances_tenant_event_checkin_idx" ON "event_attendances" USING btree ("tenant_id","event_id","checked_in_at" DESC NULLS FIRST,"id" DESC NULLS FIRST) WHERE checked_in_at is not null;--> statement-breakpoint
CREATE POLICY "event_attendances_tenant_select" ON "event_attendances" AS PERMISSIVE FOR SELECT TO "authenticated" USING (tenant_id = app.tenant_id());--> statement-breakpoint
CREATE POLICY "event_attendances_self_rsvp_insert" ON "event_attendances" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (tenant_id = app.tenant_id() and user_id = app.user_id() and status in ('going','not_going'));--> statement-breakpoint
CREATE POLICY "event_attendances_self_rsvp_update" ON "event_attendances" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (tenant_id = app.tenant_id() and user_id = app.user_id() and status in ('going','not_going')) WITH CHECK (tenant_id = app.tenant_id() and user_id = app.user_id() and status in ('going','not_going'));