-- event_checkin_attempts_total (06 code review, WR-05) — a per-CODE ceiling on one member's wrong
-- guesses, independent of the event's length. GENERATED by `drizzle-kit generate` from
-- `packages/modules/events/db/schema.ts`, byte for byte below this header, so `pnpm db:generate`
-- stays a no-op. Its companion `*_event_check_in_ceiling.sql` is the hand-written half:
-- `app.events_check_in`, still the ONLY writer of this table (no write policy, T-06-30), enforces
-- the ceiling and restarts the total when the venue code is regenerated
-- (`event_secrets.code_rotated_at` newer than `total_since`). Existing rows start at 0.

ALTER TABLE "event_checkin_attempts" ADD COLUMN "total_failed" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "event_checkin_attempts" ADD COLUMN "total_since" timestamp with time zone DEFAULT now() NOT NULL;