-- stories (05-05) — STORY-01 and STORY-03's table, and the moment `feed_comments.story_id` /
-- `feed_likes.story_id`, reserved by Phase 4 with their `num_nonnulls` CHECKs and their partial
-- unique index and docblocked as Phase 5's inheritance, finally get the foreign keys they never had.
--
-- THE FILE IS TWO HALVES, and the split is deliberate (the `20260923185730_feed_communities.sql`
-- shape, one plan later):
--
--   1. GENERATED by `drizzle-kit generate` from `packages/modules/stories/db/schema.ts` — everything
--      down to the `stories_tenant_isolation` policy, byte for byte. `pnpm db:generate` is a no-op
--      against it, which is the property that keeps the TS schema and this folder honest.
--
--   2. HAND-WRITTEN — `feed_comments_story_fk` and `feed_likes_story_fk`. They are not generated
--      because they CANNOT be: the referencing tables belong to `@rede-social/module-feed`, and
--      `turbo.json`'s boundary allowlist denies a `module -> module` package dependency (MOD-02,
--      proved by `packages/boundary-fixture`). A drizzle `.references(() => stories.id)` on those
--      columns needs exactly that import. Nothing is lost: the DATABASE enforces them either way,
--      `supabase/tests/110-communities-stories.sql` asserts both directions with positive controls,
--      and drizzle never diffs them away — the constraints are absent from the TS schema and
--      therefore absent from the snapshot `drizzle-kit generate` compares against.
--
-- WHY `expires_at` IS A DEFAULT AND NOT A GENERATED COLUMN. The obvious tightening —
-- `generated always as (published_at + interval '24 hours') stored` — is refused by Postgres:
-- `timestamptz + interval` is STABLE rather than IMMUTABLE, and a generation expression must be
-- immutable (`ERROR: generation expression is not immutable`, reproduced on this project's
-- Postgres 17.6). A column DEFAULT may be volatile, and `now()` is the TRANSACTION timestamp, so
-- `published_at` and `expires_at` are derived from the same instant. `stories_expiry_window_chk`
-- then supplies the invariant the generated column would have given for free.
--
-- WHY THERE IS NO JOB, NO TRIGGER AND NO `status` COLUMN FOR EXPIRY. STORY-03 is a READ PREDICATE.
-- A story leaves the strip because `now()` moved past `expires_at`; the ROW IS RETAINED, which is
-- what makes D-84's history and 05-08's pins possible with no extra state, and what stops a
-- member's comment vanishing because a clock passed. Adding a sweeper here would break the
-- requirement, not implement it.
--
-- WHY THE TWO FOREIGN KEYS ARE VALIDATING AND NOT `NOT VALID`: adding a foreign key takes a
-- `SHARE ROW EXCLUSIVE` lock and scans the child table to validate the existing rows. At THIS
-- migration every `feed_comments.story_id` and every `feed_likes.story_id` in every environment is
-- NULL — neither column has ever had a writer, and a NULL child never participates in a referential
-- check — so the validation is trivial and the lock is momentary. Worth recording explicitly,
-- because 05-07's migration on these same two tables will NOT be trivial: it touches rows that by
-- then exist.
--
-- WHY `ON DELETE CASCADE` HERE, unlike `feed_posts_community_fk`'s deliberate `NO ACTION`: a story
-- is never hard-deleted by the product. `deleteStory` writes `deleted_at`, expiry writes nothing at
-- all, and there is no endpoint anywhere that issues a `delete from stories`. The cascade therefore
-- describes only the one path that can reach it — a tenant being erased, which already cascades
-- from `tenants` through `stories.tenant_id` — and it keeps THAT path from failing on orphan
-- interaction rows. It is the same clause `feed_likes.post_id` and `feed_comments.post_id` already
-- carry, so a story and a post behave identically under a tenant deletion.

CREATE TABLE "stories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"author_user_id" uuid NOT NULL,
	"media_asset_id" uuid NOT NULL,
	"media_kind" text NOT NULL,
	"caption" text DEFAULT '' NOT NULL,
	"published_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() + interval '24 hours' NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"comment_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "stories_media_kind_chk" CHECK ("stories"."media_kind" in ('image','video')),
	CONSTRAINT "stories_expiry_window_chk" CHECK ("stories"."expires_at" > "stories"."published_at")
);
--> statement-breakpoint
ALTER TABLE "stories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "stories" ADD CONSTRAINT "stories_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stories" ADD CONSTRAINT "stories_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stories" ADD CONSTRAINT "stories_media_asset_id_media_assets_id_fk" FOREIGN KEY ("media_asset_id") REFERENCES "public"."media_assets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "stories_tenant_expires_idx" ON "stories" USING btree ("tenant_id","expires_at" DESC NULLS FIRST,"id" DESC NULLS FIRST) WHERE deleted_at is null;--> statement-breakpoint
CREATE POLICY "stories_tenant_isolation" ON "stories" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id()) WITH CHECK (tenant_id = app.tenant_id());

--> statement-breakpoint
-- ── HAND-WRITTEN (half 2) ──────────────────────────────────────────────────────────────────────
-- Phase 5 adds the references and NOTHING else to these two tables: `feed_comments_target_chk` and
-- `feed_likes_target_chk` already pin "exactly one target", and `feed_likes_story_uq` already makes
-- a repeat story like a no-op. The STORY-05 discriminator machinery is 05-07's, and mixing an
-- additive change with a table rewrite in one migration is how a rollback stops being possible.
ALTER TABLE "feed_comments" ADD CONSTRAINT "feed_comments_story_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "feed_likes" ADD CONSTRAINT "feed_likes_story_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE cascade;
