-- story_community_pins (05-08) — STORY-04's join, and the reason a 24 h broadcast can become a
-- community's permanent highlight.
--
-- THE FILE IS TWO HALVES, the `20260923214059_stories.sql` shape:
--
--   1. GENERATED by `drizzle-kit generate` from `packages/modules/stories/db/schema.ts` — everything
--      down to the `story_community_pins_tenant_isolation` policy, byte for byte. `pnpm db:generate`
--      is a no-op against it, which is the property that keeps the TS schema and this folder honest.
--
--   2. HAND-WRITTEN — `story_community_pins_community_fk`. It is not generated because it CANNOT
--      be: `public.communities` belongs to `@tria/module-communities`, and `turbo.json`'s boundary
--      allowlist denies a `module -> module` package dependency (MOD-02, proved by
--      `packages/boundary-fixture`). A drizzle `.references(() => communities.id)` on that column
--      needs exactly that import. Nothing is lost: the DATABASE enforces it either way,
--      `110-communities-stories.sql` and `020-tenant-isolation.sql` both assert it, and drizzle
--      never diffs it away — the constraint is absent from the TS schema and therefore absent from
--      the snapshot `drizzle-kit generate` compares against.
--
-- WHY THE PIN IS A ROW AND NOT A COLUMN. STORY-04 says "one or more communities". A boolean or a
-- timestamp on `stories` cannot represent that at all, and a denormalised count would be a second
-- writer of a fact this join already holds. The unique pair below is what makes a repeat pin a
-- no-op rather than a 409, and what makes unpin a plain delete with nothing to disambiguate.
--
-- WHY THE UNPIN IS A HARD DELETE, and the one place Phase 5 departs from the soft-delete
-- convention: a pin carries NO AUTHORED CONTENT and NO MODERATION EVIDENCE — it is a pair of ids
-- and a timestamp recording an editorial act that has since been undone. A `deleted_at` here would
-- have to be threaded through every join that reads the table, and would need a rule for what
-- re-pinning a soft-deleted pair means. `story.unpinned` is the record that it happened.
--
-- WHY THERE IS NO EXPIRY PREDICATE ANYWHERE IN THIS FEATURE. The pin ROW IS the override: the
-- community highlights read carries no `expires_at > now()` at all, which is why a pinned story is
-- visible on its community page for EVERY value of `now()` until it is unpinned. That is asserted
-- under a clock the test controls in `110-communities-stories.sql`, beside the STRIP predicate
-- refusing the same row in the same transaction — so the two surfaces are proved to disagree
-- deliberately rather than by accident.
--
-- WHY THE FOREIGN KEY IS VALIDATING AND NOT `NOT VALID`: the table is created empty in this same
-- migration, so there is nothing to scan and the lock is momentary in every environment.
--
-- ── GENERATED (half 1) ─────────────────────────────────────────────────────────────────────────
CREATE TABLE "story_community_pins" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"story_id" uuid NOT NULL,
	"community_id" uuid NOT NULL,
	"pinned_by_user_id" uuid NOT NULL,
	"pinned_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "story_community_pins" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "story_community_pins" ADD CONSTRAINT "story_community_pins_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_community_pins" ADD CONSTRAINT "story_community_pins_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_community_pins" ADD CONSTRAINT "story_community_pins_pinned_by_user_id_users_id_fk" FOREIGN KEY ("pinned_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "story_community_pins_uq" ON "story_community_pins" USING btree ("story_id","community_id");--> statement-breakpoint
CREATE INDEX "story_community_pins_tenant_community_idx" ON "story_community_pins" USING btree ("tenant_id","community_id","pinned_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE POLICY "story_community_pins_tenant_isolation" ON "story_community_pins" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id()) WITH CHECK (tenant_id = app.tenant_id());
--> statement-breakpoint
-- ── HAND-WRITTEN (half 2) ──────────────────────────────────────────────────────────────────────
-- `on delete cascade`: deleting a community is not something the product offers (archive is), but
-- if a tenant row ever cascades through it, an orphan pin pointing at a container that no longer
-- exists would be a row no read could ever explain.
ALTER TABLE "story_community_pins" ADD CONSTRAINT "story_community_pins_community_fk" FOREIGN KEY ("community_id") REFERENCES "public"."communities"("id") ON DELETE cascade;
