-- event_checkin_attempts (06-05) — the venue-code guess counter (D-217, T-06-27, T-06-30): at most 5
-- wrong codes per member per event per 15-minute window. GENERATED by `drizzle-kit generate` from
-- `packages/modules/events/db/schema.ts`, byte for byte below this header, so `pnpm db:generate`
-- stays a no-op. Its companion `*_event_check_in_function.sql` is the hand-written half: the SECURITY
-- DEFINER `app.events_check_in`, which is the ONLY writer of this table.
--
-- There is deliberately NO insert, update or delete policy: a member lane that could write here could
-- reset its own bound. The member lane reads its OWN row (`event_checkin_attempts_self_select`) and
-- nothing else. Proved by `supabase/tests/142-event-checkin.sql` (fact 11) and the isolation cases in
-- `supabase/tests/020-tenant-isolation.sql`.

CREATE TABLE "event_checkin_attempts" (
	"tenant_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"failed_count" integer DEFAULT 0 NOT NULL,
	"window_started_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event_checkin_attempts_pkey" PRIMARY KEY("tenant_id","event_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "event_checkin_attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "event_checkin_attempts" ADD CONSTRAINT "event_checkin_attempts_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_checkin_attempts" ADD CONSTRAINT "event_checkin_attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_checkin_attempts" ADD CONSTRAINT "event_checkin_attempts_event_fk" FOREIGN KEY ("tenant_id","event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "event_checkin_attempts_self_select" ON "event_checkin_attempts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (tenant_id = app.tenant_id() and user_id = app.user_id());