-- feed_community_gate_policies (08.2-03, STORE-15; D-356; RESEARCH Patterns 2 and 7, Pitfall 14) —
-- the community gate on the feed's comments and likes. GENERATED by drizzle-kit from
-- packages/modules/feed/db/schema.ts; every statement below is drizzle-kit's, unchanged. Three
-- statements, all on feed tables, nothing else touched:
--
--   1. index `feed_post_media_tenant_asset_idx` on `feed_post_media (tenant_id, media_asset_id)`:
--      the lookup of the feed body of `app.media_asset_hidden(uuid)` (Pattern 7);
--   2. policy `feed_comments_community_gate` (restrictive, select, authenticated): a POST comment is
--      visible only when its post is visible and the post's community is not locked for the caller
--      (`app.community_locked_ids()`, the kernel seam). The leading `post_id is null` keeps every
--      STORY comment visible (Pitfall 14);
--   3. policy `feed_likes_community_gate` (restrictive, insert, authenticated): no like on the
--      sample or a hidden post, and none on a comment the policy above hides (P60: 42501 even when a
--      route's guard passed just before a link committed).
--
-- Restrictive policies AND with each table's permissive `*_tenant_isolation`; while the store is off
-- or for staff claims the locked set is '{}' and both predicates are true for every row.

CREATE INDEX "feed_post_media_tenant_asset_idx" ON "feed_post_media" USING btree ("tenant_id","media_asset_id");--> statement-breakpoint
CREATE POLICY "feed_comments_community_gate" ON "feed_comments" AS RESTRICTIVE FOR SELECT TO "authenticated" USING (post_id is null or exists (
        select 1 from public.feed_posts p
         where p.id = feed_comments.post_id
           and (p.community_id is null or p.community_id <> all (coalesce((select app.community_locked_ids()), '{}'::uuid[])))));--> statement-breakpoint
CREATE POLICY "feed_likes_community_gate" ON "feed_likes" AS RESTRICTIVE FOR INSERT TO "authenticated" WITH CHECK ((post_id is null or exists (
          select 1 from public.feed_posts p
           where p.id = feed_likes.post_id
             and (p.community_id is null or p.community_id <> all (coalesce((select app.community_locked_ids()), '{}'::uuid[])))))
        and (comment_id is null or exists (
          select 1 from public.feed_comments c where c.id = feed_likes.comment_id)));