-- events (06-01) — EVENT-01 / EVENT-02's two tables: `events`, which every member of the tenant
-- reads, and `event_secrets`, the meeting URL and the venue code, which only the tenant's
-- `admin_tenant` lane can read or write (D-207, D-208, D-217).
--
-- THE FILE IS TWO HALVES, and the split is deliberate (the `20260923214059_stories.sql` shape):
--
--   1. GENERATED by `drizzle-kit generate` from `packages/modules/events/db/schema.ts`: everything
--      down to the `events_tenant_isolation` policy, byte for byte. `pnpm db:generate` is a no-op
--      against it, which keeps the TS schema and this folder honest.
--
--   2. HAND-WRITTEN: the two foreign keys that tie the tables together. drizzle-kit cannot express
--      DEFERRABLE, so they cannot live in the TS schema; they are absent from the snapshot
--      `drizzle-kit generate` diffs against, so it never tries to drop them.
--
-- WHY THE SECRETS ARE A SEPARATE TABLE. Every member lane reads `events` under
-- `events_tenant_isolation`, so any column on it is selectable by any member through RLS alone, and a
-- column privilege cannot help: an admin and a member are the SAME database role (`authenticated`),
-- told apart only by the `tenant_role` claim. `event_secrets_staff_all` reads that claim as an inline
-- literal (not a helper function, which would have to exist before a statement drizzle-kit owns).
--
-- WHY THE TWO FOREIGN KEYS ARE DEFERRED TO COMMIT:
--   - `event_secrets_event_fk (tenant_id, event_id, event_format) -> events (tenant_id, id, format)`
--     carries the D-213 venue-XOR-URL rule ACROSS the two tables through a redundant discriminator
--     (the D-53 pattern): an online event's secrets row must say `online`, and
--     `event_secrets_url_chk` then requires its `https:` URL. A format switch (D-214 keeps every
--     field editable) updates `events.format` and `event_secrets.{event_format, meeting_url}` in one
--     transaction; with an immediate FK no statement order satisfies both the FK and the CHECKs.
--   - `events_secrets_fk (id) -> event_secrets (event_id)` makes "every event has exactly one
--     secrets row" a commit-time fact: a transaction that wrote only the `events` half cannot
--     commit (EVENT-01 concurrency, create half).
--   Referential ACTIONS cannot be deferred, only the check: `on delete cascade` still fires
--   immediately when an event is deleted, while the update/insert check waits for commit. pgTAP
--   (`supabase/tests/140-events.sql`) proves both with `set constraints all immediate`, because a
--   test file that rolls back would otherwise never reach a commit-time check (Pitfall 4).

CREATE TABLE "event_secrets" (
	"event_id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"event_format" text NOT NULL,
	"checkin_code" text NOT NULL,
	"meeting_url" text,
	"code_rotated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event_secrets_url_chk" CHECK (("event_secrets"."event_format" = 'online') = ("event_secrets"."meeting_url" is not null)),
	CONSTRAINT "event_secrets_https_chk" CHECK ("event_secrets"."meeting_url" is null or lower("event_secrets"."meeting_url") like 'https://%'),
	CONSTRAINT "event_secrets_code_chk" CHECK ("event_secrets"."checkin_code" ~ '^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{4}$')
);
--> statement-breakpoint
ALTER TABLE "event_secrets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_by_user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"cover_asset_id" uuid,
	"format" text NOT NULL,
	"venue_name" text,
	"address" text,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"cancelled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "events_format_chk" CHECK ("events"."format" in ('in_person','online')),
	CONSTRAINT "events_status_chk" CHECK ("events"."status" in ('active','cancelled')),
	CONSTRAINT "events_window_chk" CHECK ("events"."ends_at" > "events"."starts_at"),
	CONSTRAINT "events_location_chk" CHECK (("events"."format" = 'in_person' and "events"."venue_name" is not null and "events"."address" is not null and length(btrim("events"."venue_name")) > 0 and length(btrim("events"."address")) > 0) or ("events"."format" = 'online' and "events"."venue_name" is null and "events"."address" is null)),
	CONSTRAINT "events_cancelled_at_chk" CHECK (("events"."status" = 'cancelled') = ("events"."cancelled_at" is not null))
);
--> statement-breakpoint
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "event_secrets" ADD CONSTRAINT "event_secrets_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_cover_asset_id_media_assets_id_fk" FOREIGN KEY ("cover_asset_id") REFERENCES "public"."media_assets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "event_secrets_tenant_event_uq" ON "event_secrets" USING btree ("tenant_id","event_id");--> statement-breakpoint
CREATE UNIQUE INDEX "events_tenant_id_uq" ON "events" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "events_tenant_id_format_uq" ON "events" USING btree ("tenant_id","id","format");--> statement-breakpoint
CREATE INDEX "events_tenant_starts_idx" ON "events" USING btree ("tenant_id","starts_at","id") WHERE deleted_at is null;--> statement-breakpoint
CREATE INDEX "events_tenant_ends_idx" ON "events" USING btree ("tenant_id","ends_at" DESC NULLS FIRST,"id" DESC NULLS FIRST) WHERE deleted_at is null;--> statement-breakpoint
CREATE POLICY "event_secrets_staff_all" ON "event_secrets" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id() and app.tenant_role() = 'admin_tenant') WITH CHECK (tenant_id = app.tenant_id() and app.tenant_role() = 'admin_tenant');--> statement-breakpoint
CREATE POLICY "events_tenant_isolation" ON "events" AS PERMISSIVE FOR ALL TO "authenticated" USING (tenant_id = app.tenant_id()) WITH CHECK (tenant_id = app.tenant_id());

--> statement-breakpoint
-- ── HAND-WRITTEN (half 2) ──────────────────────────────────────────────────────────────────────
-- The XOR across the two tables: the secrets row's discriminator must match its event's format.
ALTER TABLE "event_secrets" ADD CONSTRAINT "event_secrets_event_fk" FOREIGN KEY ("tenant_id","event_id","event_format") REFERENCES "public"."events"("tenant_id","id","format") ON DELETE cascade DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
-- Existence: every event has its secrets row, checked at commit.
ALTER TABLE "events" ADD CONSTRAINT "events_secrets_fk" FOREIGN KEY ("id") REFERENCES "public"."event_secrets"("event_id") DEFERRABLE INITIALLY DEFERRED;
