DROP POLICY "chat_conversations_access" ON "chat_conversations" CASCADE;--> statement-breakpoint
DROP POLICY "chat_messages_access" ON "chat_messages" CASCADE;--> statement-breakpoint
DROP POLICY "chat_participants_access" ON "chat_participants" CASCADE;--> statement-breakpoint
CREATE POLICY "chat_conversations_select" ON "chat_conversations" AS PERMISSIVE FOR SELECT TO "authenticated" USING (tenant_id = app.tenant_id() and ((kind = 'support' and app.tenant_role() in ('admin_tenant', 'support_tenant')) or created_by_user_id = app.user_id() or exists (select 1 from public.chat_participants p where p.conversation_id = chat_conversations.id and p.tenant_id = app.tenant_id() and p.user_id = app.user_id())));--> statement-breakpoint
CREATE POLICY "chat_conversations_insert" ON "chat_conversations" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (tenant_id = app.tenant_id() and created_by_user_id = app.user_id() and last_seq = 0 and last_staff_seq = 0 and staff_last_read_seq = 0 and last_message_side is null and last_message_at is null);--> statement-breakpoint
CREATE POLICY "chat_conversations_staff_update" ON "chat_conversations" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (tenant_id = app.tenant_id() and kind = 'support' and app.tenant_role() in ('admin_tenant', 'support_tenant')) WITH CHECK (tenant_id = app.tenant_id() and kind = 'support' and app.tenant_role() in ('admin_tenant', 'support_tenant'));--> statement-breakpoint
CREATE POLICY "chat_messages_select" ON "chat_messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING (tenant_id = app.tenant_id() and exists (select 1 from public.chat_conversations c where c.id = chat_messages.conversation_id));--> statement-breakpoint
CREATE POLICY "chat_messages_insert" ON "chat_messages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (tenant_id = app.tenant_id() and author_user_id = app.user_id() and ((author_side = 'staff' and app.tenant_role() in ('admin_tenant', 'support_tenant') and exists (select 1 from public.chat_conversations c where c.id = chat_messages.conversation_id and c.kind = 'support')) or (author_side = 'member' and exists (select 1 from public.chat_participants p where p.conversation_id = chat_messages.conversation_id and p.tenant_id = app.tenant_id() and p.user_id = app.user_id()))));--> statement-breakpoint
CREATE POLICY "chat_participants_select" ON "chat_participants" AS PERMISSIVE FOR SELECT TO "authenticated" USING (tenant_id = app.tenant_id() and (user_id = app.user_id() or app.tenant_role() in ('admin_tenant', 'support_tenant')));--> statement-breakpoint
CREATE POLICY "chat_participants_insert" ON "chat_participants" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (tenant_id = app.tenant_id() and user_id = app.user_id() and role = 'member' and exists (select 1 from public.chat_conversations c where c.id = chat_participants.conversation_id and c.tenant_id = app.tenant_id() and c.created_by_user_id = app.user_id()));--> statement-breakpoint
CREATE POLICY "chat_participants_update_own" ON "chat_participants" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (tenant_id = app.tenant_id() and user_id = app.user_id()) WITH CHECK (tenant_id = app.tenant_id() and user_id = app.user_id());